### ISSUE TITLE
Delete Nodes and Try to Keep Shape plugin is not working?

### ISSUE THREAD

**Issue by elenage** [mekkablue/Glyphs-Scripts#105]
No errors, no warnings, nothing. It just does nothing to the selected path...

**Comment by schriftgestalt** [comment]
I send you a pull request.

**Comment by mekkablue** [comment]
It works just fine for me. Are you sure you have the latest version of the script?

**Comment by elenage** [comment]
Positive. I've checked and replaced the script twice.

**Comment by mekkablue** [comment]
Can you upload a QuickCast so I can see how you are using the script?

**Comment by mekkablue** [comment]
Or contact me on Skype and share your screen. Skypename is schriftlabor_rainer.

**Comment by elenage** [comment]
Here it is http://quick.as/dPRVue2dJ
Funny thing - the script works with a randomly drawn path but not with the one i need it work.... (you can see that in the video)

**Comment by mekkablue** [comment]
That is how it is supposed to work.
1. It can only simplify curves, not straight lines.
2. It is not designed to be applied on a _complete_ path.

But that gives me an idea, that I could turn all these lines into curves before removing them. You can try yourself, and run _Insert BCPs into Straight Lines_ before running _Delete Nodes and Try to Keep Shape_.

**Comment by elenage** [comment]
I have tried this before reporting the issue... The _Insert BCP into Straight Lines_ doesn't work either (actually _Insert BCP into Straight Lines_  doesn't work with any curve in any file).
A have tried selecting a part of the path (4 to 10 nodes) and the whole path - doesn't work in both cases.  
You can take a look at the source file if you're interested (I've removed most of the glyphs, leaving just few). https://dl.dropboxusercontent.com/u/22977838/test.glyphs.

**Comment by mekkablue** [comment]
It is not supposed to work on a curve. _Insert BCPs_ does what it says, it takes all straight lines in a glyph, and inserts BCPs (handles) to them, technically turning straight lines into curves. It does not respect your node selection.

Think of it this way: It is the equivalent of Option-clicking every straight line segment.

**Comment by elenage** [comment]
I do understand what both of the scripts are supposed to do but can't make even the _Insert BCPs_ script to work...
Can you tell me what am I doing wrong? (see screenshots)

1. [I create a shape](https://dl.dropboxusercontent.com/u/22977838/Screen%20Shot%202016-07-21%20at%2018.35.46.png) that contains only straight segments (no handles whatsoever) , 
2. I select 5 nodes out of 10 (4 straight segments), run the _Insert BCPs_ script - [nothing happens](https://dl.dropboxusercontent.com/u/22977838/Screen%20Shot%202016-07-21%20at%2018.36.00.png).

**Comment by mekkablue** [comment]
The selection is superfluous. The script ignores the node selection. It should still insert BCPs though. I cannot reproduce the non-functioning. Is there no message in the macro window?

**Comment by elenage** [comment]
Yes, there is a message there (had to open Macro panel manually - it didn't open on the error). Here is the message:
_Start
Traceback (most recent call last):
  File "Insert BCPs into straight segments.py", line 12, in <module>
    selection = selectedLayers[0].selection()
TypeError: 'LayerSelectionProxy' object is not callable
End_

**Comment by elenage** [comment]
Seems like I was using an outdated version of the script (even though I've checked twice!). After code replacement it seems to be working fine.
Thank you for all your help, Rainer!
