### ISSUE TITLE
Stitcher Script Problem

### ISSUE THREAD

**Issue by alannamun** [mekkablue/Glyphs-Scripts#109]
Hey there!

This is for the stitcher script. I am running it in the macro panel.

I continue to get this error: "Could not place components at intervals of 151.9 units." (or whatever unit I put in). 

I traced the error back to potentially originating in the 'getFineGrainPointsForPath' function, but I don't totally understand what is failing?

This is the file I was using:
[bulb-test.zip](https://github.com/mekkablue/Glyphs-Scripts/files/491829/bulb-test.zip)

Any ideas?

Thanks!

**Comment by mekkablue** [comment]
Are you sure you have the latest version of the script?

**Comment by mekkablue** [comment]
I just updated the script, there was a bug that prevented the origin anchor from working properly. And there is still an issue with closed paths: an extra, superfluous coordinate is being calculated. I could not figure that one out yet. But the script is working.

**Comment by alannamun** [comment]
Thanks for looking into it. I still can't get this to work. 

I have the latest version of both glyphs and the script. I have Vanilla installed. I have a component with an anchor called origin. I have a circle in the "O" glyph (closed path). I still get the same error if I hit stitch.

This morning I also tried: creating a whole new file, re-installing glyphs, re-installing vanilla, deleting all the other scripts in the script folder, restarting my computer. Everything I could think of

I'm not sure how to help you recreate the error, but let me know if you have any ideas, maybe I'm doing something wrong? 

Thanks!!!

**Comment by mekkablue** [comment]
Can you make a QuickCast? And post the link here?

**Comment by alannamun** [comment]
Okay! I got it to work with the help of an older version of the script that @kennethormandy had in his scripts folder. He last updated the folder in February 2015 (I'll attach the version). 

If I used the February version in the macro panel it didn't work, BUT, if I put the February version into the scripts folder it works from both the menu and macro panel. And for added weirdness, if the February version is in the scripts folder, the latest version of the script works from the macro panel. 

[Stitcher.py.zip](https://github.com/mekkablue/Glyphs-Scripts/files/496130/Stitcher.py.zip)

**Comment by mekkablue** [comment]
Can you try clicking on _Glyphs > Preferences > Addons > Modules > Install Modules_?

**Comment by alannamun** [comment]
Yep, I did that to install vanilla before. I just did it again to make sure. 

I still can't get the latest version of the script to work. I can use the February version from the script menu (If I change a setting like the intervals in the input boxes it crashes the whole program, but I can use the live slider and it places the bulbs no problem).
