### ISSUE TITLE
Running "Show previous instance" preview bug

### ISSUE THREAD

**Issue by synthview** [mekkablue/Glyphs-Scripts#112]
Hello!
Let’s say I have some instances appearing as following in the preview drag n drop menu in G2:
```
— (the 1st item = show master not instance)
instance 1
instance 2
instance N…
```
When I am on instance 2 and run “Show previous instance”, G2 shows the master (not Instance 1) but displays the name of Instance 1 (not —) = I never preview instance 1 and have wrong names.

When I am on Instance N and run “Show next instance”, I see the master but the label keeps  Instance N.

Thanks

**Comment by mekkablue** [comment]
I can reproduce it, but don’t know yet how to fix that.

**Comment by synthview** [comment]
Ok no problem. I’ve also noticed the preview loses synchro when switching tabs

**Comment by impallari** [comment]
I have notice a similar issue when running my "instance show/hide" set of macros (https://github.com/impallari/Impallari-Glyphs-Macros/tree/master/Instances/Show%20Hide).
In previews versions the preview are updated automatically, now I need to select a new glyphs for the preview area to get updated.

**Comment by mekkablue** [comment]
Should be fixed with the update I just uploaded.
