### ISSUE TITLE
Floating Features doesn't update kerning values

### ISSUE THREAD

**Issue by weiweihuanghuang** [mekkablue/Glyphs-Scripts#115]
It doesn't update kerning values displayed when the cursor is between 2 glyphs.

**Comment by mekkablue** [comment]
I don’t understand. What does that have to do with Floating Features? The script is not supposed to update any values.

**Comment by weiweihuanghuang** [comment]
I mean the value displayed in the kerning info hover between two glyphs doesn't update when you activate a feature, as it is a new glyph pair now, it still displays the kerning value of the old pair before the feature is updated.

**Comment by mekkablue** [comment]
Just tested it and can confirm it works as expected in V.956.

**Comment by weiweihuanghuang** [comment]
Please check my video

/V/A kerning is -60,
/v.sc/a.sc is -70

but activating it using this script shows -100 (not sure where that came from), along with the following issue where the kerning hover disappears:

 https://forum.glyphsapp.com/t/clicking-the-cursor-hides-the-kerning-info-hover-behind-the-metrics-hover/5645/6

**Comment by mekkablue** [comment]
Sorry, I still cannot reproduce it. It works as expected for me in Version 956. Therefore, I would say it does not have anything to do with the _Floating Features_ script, so I will keep this issue here closed.

**Comment by weiweihuanghuang** [comment]
Can you try it with my file https://github.com/weiweihuanghuang/Work-Sans/blob/master/sources/Work%20Sans.glyphs

**Comment by mekkablue** [comment]
I could reproduce it. Recreating OT features from scratch fixes it, though. I cannot tell what caused the problem. I can only assume it has something to do with the feature code.
