### ISSUE TITLE
New Tab with Unaligned Compounds for Every Master

### ISSUE THREAD

**Issue by kosbarts** [mekkablue/Glyphs-Scripts#116]
Hey Eric, 

I think you have removed this one. I had it and I tried it and it just gave me a list with all glyphs with components. I made one change and now it works. 

From:
for thisComponent in thisLayer.components:
				if thisComponent.disableAlignment:
					everythingAligned = False
To:for thisComponent in thisLayer.components:
				if not thisComponent.automaticAlignment:
					everythingAligned = False

Just letting you know.

Here is your whole script:

#MenuTitle: New Tab with Unaligned Compounds for Every Master
# -*- coding: utf-8 -*-
__doc__="""
Opens a new tab with glyphs that have unaligned components. Inserts a new paragraph for a every master. Useful for finding misaligned accents.
"""

import GlyphsApp

thisFont = Glyphs.font # frontmost font
thisFontMaster = thisFont.selectedFontMaster # active master
listOfSelectedLayers = thisFont.selectedLayers # active layers of selected glyphs			
tabString = ""

for thisFontMaster in thisFont.masters:
	tabString += "\n\n%s:\n" % thisFontMaster.name
	for thisGlyph in thisFont.glyphs:
		thisLayer = thisGlyph.layers[thisFontMaster.id]
		if len( thisLayer.components ) > 0 and len( thisLayer.paths ) == 0:
			everythingAligned = True
			for thisComponent in thisLayer.components:
				if not thisComponent.automaticAlignment:
					everythingAligned = False
			if not everythingAligned:
				tabString += "/%s" % thisGlyph.name
				
# opens new Edit tab:
from PyObjCTools.AppHelper import callAfter
callAfter( Glyphs.currentDocument.windowController().addTabWithString_, tabString[2:-1] )

**Comment by mekkablue** [comment]
Thanks :) I removed the script because you can do this with a Smart Filter now.
