### ISSUE TITLE
Show previous instance always skips 1st instance

### ISSUE THREAD

**Issue by synthview** [mekkablue/Glyphs-Scripts#118]
exemple of an instances dropdown menu for the preview: 
```
—
light
normal
bold
bold 2
bold 3

```
When I’m visualising “normal” and run “Show previous instance” script to go to -1 (to light), the preview shows — (= current master “as it is”)

**Comment by mekkablue** [comment]
I think I fixed it now.

**Comment by synthview** [comment]
perfect it works, thanks!! :)
