### ISSUE TITLE
Insert Instances Script causing Glyphs to "Not Respond"

### ISSUE THREAD

**Issue by jakefleming** [mekkablue/Glyphs-Scripts#121]
MacOS Sierra 10.12.3
Glyphsapp Version 2.4.1

Here's a short video demonstrating the issue: https://dl.dropboxusercontent.com/u/24282857/bugs/mekkablue-insertinstances.mp4

Happy to provide anything else you need to reproduce.

**Comment by mekkablue** [comment]
I cannot reproduce this in 2.4.2 (1006) and macOS 10.12.4 (16E195). Consider reinstalling the modules in the app preferences. Or send me your .glyphs file by email.
