### ISSUE TITLE
Merge All Other Masters in Current Master.py

### ISSUE THREAD

**Issue by MajusCorp** [mekkablue/Glyphs-Scripts#123]
Can this script be modified so that it also copies the width of the copied glyph to the current master?

**Comment by MajusCorp** [comment]
The glyph width, as defined on page 70 of the manual. It is the only glyph width I know of.

**Comment by mekkablue** [comment]
Example. When the scripts merges three masters into the first, there are potentially 4 different widths to deal with: the original one, and the widths of the three other masters. Which one should it take? And why? And should that be a function of this script in the first place?

**Comment by MajusCorp** [comment]
Sorry, I'm thinking in terms of copying glyphs from only one additional master. I've just discovered another of your scripts that will do just that, which solves my problem.
