### ISSUE TITLE
Stitcher request

### ISSUE THREAD

**Issue by Tosche** [mekkablue/Glyphs-Scripts#124]
I would like Stitcher to always have the component at the end, and redistribute the rest automatically. It is a bit frustrating that the other end finishes at random timing, and it's only based on your slider control (which you have to adjust every time per path) and starting node position.

**Comment by mekkablue** [comment]
This is close to impossible to calculate reliably with the underlying math (precise length of PS segment). It is probably best practice to leave a bit of path for uncertainty at the end.

**Comment by Tosche** [comment]
Never mind, solved it myself :)
