### ISSUE TITLE
Steal SideBearings From One Master to another in the same Font/Glyphs file

### ISSUE THREAD

**Issue by Avantino** [mekkablue/Glyphs-Scripts#129]
1. The option to run script over selected glyphs only (if possible)
2. Need to Double check  glyphs that are built with several components ... it seems they loose coordinates and result a mess.
as mentioned through the forum;

**Comment by mekkablue** [comment]
> option to run script over selected glyphs only

This is the script's default behaviour. Do you have the latest version?

**Comment by mekkablue** [comment]
I had a look at it again. The script works as expected. Make sure you have the latest version.

> Need to Double check glyphs that are built with several components

This is to be expected. You can run into trouble if you: select original glyph and the compound, and the compound does not have auto-alignment. You must make sure you only select the glyphs you want to change the SBs for. If you shift a glyph, all its components are shifted as well. You can avoid a lot of trouble with auto-alignment.
