### ISSUE TITLE
Select Same Color script request

### ISSUE THREAD

**Issue by LibertyType** [mekkablue/Glyphs-Scripts#132]
Can _Select Same Color.py_ be changed so that it will also select multi-colors, i.e. Label Key colors?

**Comment by weiweihuanghuang** [comment]
Made this here https://gist.github.com/weiweihuanghuang/4ed1f3556b4911bad55cbd1a8dfa31fb too lazy to make a fork request :)

**Comment by LibertyType** [comment]
Thanks. Works great!
