### ISSUE TITLE
Steal Sidebearings

### ISSUE THREAD

**Issue by designiq** [mekkablue/Glyphs-Scripts#135]
Hi Erich, I wish the "Steal Sidebearings" script would copy keys for glyph width as well. My alternative "stamp" letters A.ss01 and A.ss02 have this formula: LSB = "A", Width = "A", RSB is calculated automatically. When I run your script, I only get LSB = "A", Width is unfortunately not set as a reference to "A" but rather the actual numerical value is used. Thanks, F.

**Comment by designiq** [comment]
Edit: It works, but the Font Italic angle must be set to 0 degrees. If the font original font has zero degrees and the target font 10 degrees, the key is not displayed in Glyphs. I changed the angle to 0 and than back to 10 and I can see the keys now. Strange.

**Comment by mekkablue** [comment]
There is a _Batch Metrics Keys_ script in Tosche’s repository that should be able to do that. (Not copy the keys but batch-apply them.)

**Comment by alexeiva** [comment]
You can try my '[Inherit Metrics Keys](https://github.com/alexeiva/alexei-glyphs-scripts#metrics)' for this task

**Comment by mekkablue** [comment]
I updated the script and renamed it to _Steal Metrics._

**Comment by mekkablue** [comment]
Sorry commit 8660aa4 was wrongly titled, was meant for #156.
