### ISSUE TITLE
Glyphs - Diacritic Ligature Maker

### ISSUE THREAD

**Issue by diegommaldo** [mekkablue/Glyphs-Scripts#136]
Hi as we talked on Glyphs forum, not sure what this error means, but this is what happens:

Start
Creating variations for T_E.dlig:
Traceback (most recent call last):
  File "Diacritic Ligature Maker.py", line 100, in <module>
    listOfLigatures = process( thisGlyphName )
  File "Diacritic Ligature Maker.py", line 75, in process
    diacriticLetterLists = [ [n]+namesOfGlyphsContainingThisComponent(n) for n in namesOfLigatureLetters ]
  File "Diacritic Ligature Maker.py", line 32, in namesOfGlyphsContainingThisComponent
    listOfGlyphs = selectTool._glyphsContainingComponentWithName_font_masterID_( componentName, thisFont, thisFontMasterID )
AttributeError: 'GSToolSelect' object has no attribute '_glyphsContainingComponentWithName_font_masterID_'
End

**Comment by mekkablue** [comment]
That line only gets called if the previous function causes an error. Which version of Glyph are you using?

**Comment by diegommaldo** [comment]
Sorry, I'm using Version 2.5b (1105) macOS - 10.13.2

**Comment by mekkablue** [comment]
I cannot reproduce the problem. It may have already been fixed. Please make sure you have the latest version of the scripts.
