### ISSUE TITLE
Floating Features.py no longer updates preview panel?

### ISSUE THREAD

**Issue by weiweihuanghuang** [mekkablue/Glyphs-Scripts#138]
It used to update the Preview Panel but since 1108 it doesn't do that anymore, and you have to move the cursor for it to update...

**Comment by schriftgestalt** [comment]
I needed to fix something in Glyphs.

**Comment by weiweihuanghuang** [comment]
@schriftgestalt still like this in Version 2.5b (1114)

**Comment by schriftgestalt** [comment]
I have fixed the script.
