### ISSUE TITLE
Anchor Mover 2 crash when switching masters

### ISSUE THREAD

**Issue by kontur** [mekkablue/Glyphs-Scripts#139]
I haven't dug into the reason for this, but I reliably get program crashes when doing the following in Version 2.5b (1111):

- Select some glyphs in the font view
- Select Anchor Mover 2.0
- Apply a transformation (i.e. current _top to x-height)
- **Leave the Anchor Mover window open**
- Click into the font view
- Switch to a different master
- Click in the Anchor Mover window to apply the same transform to the same selected glyphs in the now selected master

This crashes the app.

**Comment by mekkablue** [comment]
Can reproduce if one master lacks the anchor in one glyph. Looking into it…

**Comment by mekkablue** [comment]
The latest update should fix this.

**Comment by kontur** [comment]
Yep, can confirm this no longer crashes. Thanks for the quick fix 👍
