### ISSUE TITLE
Copy Layer to Layer

### ISSUE THREAD

**Issue by LibertyType** [mekkablue/Glyphs-Scripts#140]
Copy Layer to Layer (latest version) is not working in G2 [1115]. Previously a small window would appear allowing for selection of layers and other things; it no longer appears, and nothing is copied.

**Comment by LibertyType** [comment]
More testing done today and determined that the script works just fine in OS X 10.11.6. It does not work in OS X 10.12.6 (Sierra).

Macro window output:
Start
Traceback (most recent call last):
  File "Copy Layer to Layer.py", line 276, in <module>
    CopyLayerToLayer()
  File "Copy Layer to Layer.py", line 45, in __init__
    self.w.masterSource = vanilla.PopUpButton((120, 12+20, -15, 17), self.GetMasterNames("source"), sizeStyle='small', callback=self.MasterChangeCallback)
  File "Copy Layer to Layer.py", line 117, in GetMasterNames
    thisFont = Glyphs.fonts[fontIndex]
  File "GlyphsApp/GlyphsApp/__init__.py", line 1330, in __getitem__
KeyError
End

**Comment by mekkablue** [comment]
The script needs a major rewrite. I hope to get around to it one of these days.

**Comment by LibertyType** [comment]
Asking for any info when this might be fixed for Sierra.

**Comment by mekkablue** [comment]
Within the coming 2 weeks, I hope. Will need to rewrite it from scratch.

**Comment by LibertyType** [comment]
Thanks. It's an important script for a lot of us.  :-)

**Comment by mekkablue** [comment]
Most of its functionality is covered by _Paste Special_ (Cmd-Opt-V).

**Comment by weiweihuanghuang** [comment]
Paste special also does weird things I don't understand though ... https://forum.glyphsapp.com/t/copy-paste-special-bug/5419

**Comment by mekkablue** [comment]
The script should work again.
