### ISSUE TITLE
Webfont Test HTML.py doesn’t work

### ISSUE THREAD

**Issue by synthview** [mekkablue/Glyphs-Scripts#142]
Hi,
Test HTML.py does not save. I think there is some issue with the path, as in macro it shows me a somehow weird path (I’ve omitted it for privacy).

Here the macro record:

Start
Preparing Test HTML for:
  WOFF *******
  WOFF2 *******
  EOT *******
Traceback (most recent call last):
  File "Webfont Test HTML.py", line 289, in <module>
    if saveFileInLocation( content=htmlContent, fileName="fonttest.html", filePath=exportPath ):
  File "Webfont Test HTML.py", line 13, in saveFileInLocation
    f = open( saveFileLocation, 'w' )
IOError: [Errno 2] No such file or directory: u'*******/webfonts/fonttest.html'
End

**Comment by mekkablue** [comment]
The script works as expected for me. The error message says it cannot resolve `*******/webfonts/fonttest.html`. Somehow it thinks you have a folder called `*******`?

**Comment by synthview** [comment]
But the script chosen a weird folder (it was about an old project, but nothing related to type design). Is there any way to set the path? Where the path G2 tries to use comes from?

**Comment by mekkablue** [comment]
It is the most recent path you exported webfonts to.

**Comment by synthview** [comment]
ohh I see. Question: the webfont’s export path is relative to the app or specific to each .glyphs file?

**Comment by mekkablue** [comment]
The webfont export path is what you set when you choose _File > Export… > Webfonts._ It does not matter whether you have exported with or without the _Export Destination_ option.
