### ISSUE TITLE
Variable Font Test HTML.py /// DON'T WORK IN CUTTING EDGE 1125

### ISSUE THREAD

**Issue by etunni** [mekkablue/Glyphs-Scripts#145]
Hi Rainer,
With the latest cutting edge this script don't work.

**This is the message at macro window.**
Start
Preparing Test HTML for: Gradsix
Traceback (most recent call last):
  File "Variable Font Test HTML.py", line 269, in <module>
    ( "###sliders###", allOTVarSliders(thisFont) ),
  File "Variable Font Test HTML.py", line 51, in allOTVarSliders
    thisMaster.customValue1(),
TypeError: 'float' object is not callable
End

**Comment by etunni** [comment]
Hi,
The same script works properly with cutting edge 1123.
What parenthesis have to be removed?

**Comment by schriftgestalt** [comment]
> The same script works properly with cutting edge 1123.

I know

> What parenthesis have to be removed?

the ones after `.customValue1()`

**Comment by mekkablue** [comment]
Fixed in the latest update.
