### ISSUE TITLE
Variable Font Test HTML script doesn't respect the "Axis Location" value

### ISSUE THREAD

**Issue by dyyybek** [mekkablue/Glyphs-Scripts#149]
If a user has added a "Axis Location" custom parameter then the script should take that into account, otherwise the test is not fully functional.

**Comment by mekkablue** [comment]
Yes, it is a known issue, but I will not get around to changing this any time soon. The HTML contains a warning about that.

**Comment by mekkablue** [comment]
I just uploaded a new version that checks if all masters have an axis location parameter, and if so, prefers them over the raw values.
