### ISSUE TITLE
Delete Nodes and Try to Keep Shape produces different results

### ISSUE THREAD

**Issue by harbortype** [mekkablue/Glyphs-Scripts#150]
The result from _Delete Nodes and Try to Keep Shape_ is sometimes different than the result from deleting a node with the select tool. For example, try deleting the marked node in the attached file. 

Glyphs 2.5.2 (1176)

[deletenodes.glyphs.zip](https://github.com/mekkablue/Glyphs-Scripts/files/2549589/deletenodes.glyphs.zip)

![deletenodes](https://user-images.githubusercontent.com/10968309/48012702-c1f7d500-e109-11e8-9f20-51244ce6c144.png)

**Comment by mekkablue** [comment]
Thanks for reporting. The script does not balance the handles, which keeps the shape better in some cases.

I added an option to the script: If you hold down Shift while running the script, it will balance the handles, yielding the result on the right in your screenshot.
