### ISSUE TITLE
Steal kerning from Indesign: Not authorized to send Apple events

### ISSUE THREAD

**Issue by chrisjansky** [mekkablue/Glyphs-Scripts#152]
Running Steal kerning from Indesign with Glyphs 2.6.1 and Indesign CC 2018 on MacOS Mojave 10.14, I get the following error:

![screenshot 2019-01-10 at 19 22 10](https://user-images.githubusercontent.com/5342612/50988491-0ee29800-150d-11e9-8216-ee4065cd783e.png)

Any idea please how to fix this? I tried adding Glyphs to application with full disk access, but no luck. Is there any specific application I need to grant access to?

Thanks!

**Comment by chrisjansky** [comment]
Researching possible solutions, I found https://www.felix-schwarz.org/blog/2018/08/new-apple-event-apis-in-macos-mojave

I do not get any prompt asking me to grant permission though, might it be related to the description missing in .plist?

**Comment by schriftgestalt** [comment]
Thanks for the link. I need to add some of that to Glyphs.

**Comment by abcdpotato** [comment]
> Researching possible solutions, I found https://www.felix-schwarz.org/blog/2018/08/new-apple-event-apis-in-macos-mojave
> 
> I do not get any prompt asking me to grant permission though, might it be related to the description missing in .plist?

Hi Christian. Did you ever find a work-around?

**Comment by chrisjansky** [comment]
@abcdpotato Hey, unfortunately not. I gave up for the time being.

@schriftgestalt could you please update us if that‘s something to be fixed in one of the upcoming updates?

**Comment by abcdpotato** [comment]
@chrisjansky Hey man, I figured out a work-around. I just split the script into two parts to be run separately. The first script is run as a standalone script outside of Glyphs, and it saves the kerning data to a txt file. The second script you just run through Glyphs like normal and it applies the kerning data stored in the txt file.

The files are here if you need them:
[https://github.com/abcdpotato/glyphs/tree/master/Steal%20Kerning%20from%20InDesign](url)

**Comment by chrisjansky** [comment]
@abcdpotato Awesome! I'll try it out later today. Really appreciated, thanks!
