### ISSUE TITLE
Var font text-shadow CSS hack no longer needed (VF  HTML test script)

### ISSUE THREAD

**Issue by thundernixon** [mekkablue/Glyphs-Scripts#153]
In [Variable Font Test HTML.py](https://github.com/mekkablue/Glyphs-Scripts/blob/f8b86a0adff924ddb7866dafe5ebac9b65fcc78f/Test/Variable%20Font%20Test%20HTML.py), you use `text-shadow: 0 0;` as a CSS hack to prevent hairlines showing up in variable fonts. 

The good news is, browsers have solved this rendering bug! I haven't seen it show up in chrome, firefox, or safari for at least a few months. 

So, I think it can be safely removed, unless you expect a large number of users on medium-old versions of browsers.

**Comment by mekkablue** [comment]
Thx!
