### ISSUE TITLE
Why should glyphs have only one Unicode?

### ISSUE THREAD

**Issue by davelab6** [mekkablue/Glyphs-Scripts#155]
In your preflight script, you have a check for glyphs to only have one Unicode. Could you explain why that's a problem?

This came up in the context of

https://github.com/googlefonts/fontbakery/issues/2345

**Comment by mekkablue** [comment]
The script is terribly outdated and should not be used as a reference anymore. I am thinking of pulling it altogether. If someone wants to take it over into their repo and update it, feel free.

**Comment by felipesanches** [comment]
I think this issue can be closed, then. Thanks for the clarification.

**Comment by davelab6** [comment]
Still I'm curious about the problem. However, perhaps Marc Foley or the GF
glyphs scripts checker scripts can be a good home for these methods, and
the script here can just do nothing other than print "go there"?

**Comment by mekkablue** [comment]
Update: some software does have problems with multiple Unicodes. Adobe’s APPE has been reported to me, for instance.
