### ISSUE TITLE
Auto Bumper

### ISSUE THREAD

**Issue by chofrosubo** [mekkablue/Glyphs-Scripts#162]
![Bildschirmfoto 2019-08-08 um 17 00 54](https://user-images.githubusercontent.com/16613889/62714083-2b40a780-b9fe-11e9-9401-e38c5e9e668c.png)
<img width="577" alt="Bildschirmfoto 2019-08-08 um 17 00 05" src="https://user-images.githubusercontent.com/16613889/62714085-2bd93e00-b9fe-11e9-9c08-fb7b5f6b7ccb.png">

**Comment by chofrosubo** [comment]
still not working…

<img width="538" alt="Bildschirmfoto 2019-08-14 um 10 08 24" src="https://user-images.githubusercontent.com/16613889/63004851-9dd8d980-be7b-11e9-8ddf-0e2a9e87c9e0.png">

**Comment by mekkablue** [comment]
Should be fixed now.
