### ISSUE TITLE
Center Glyphs not working

### ISSUE THREAD

**Issue by guidoferreyra** [mekkablue/Glyphs-Scripts#165]
I just updated to Glyphs version 2.6.2 (1268) and Center Glyphs stopped working. Tried to debug it but I couldn’t :(
Here the console error log.

```
Traceback (most recent call last):
  File "Center Glyphs.py", line 48, in <module>
    thisLayer.applyTransform( shiftMatrix )
  File "GlyphsApp/GlyphsApp/__init__.py", line 6409, in __GSLayer_applyTransform__
AttributeError: 'NSKVONotifying_GSLayer' object has no attribute 'transform_checkForSelection_doComponents_'
End
```

**Comment by mekkablue** [comment]
Cannot reproduce in build 1270. Maybe update to the latest cutting edge version?

**Comment by guidoferreyra** [comment]
It’s working on cutting edge version but is any way to make it work on stable version? Any ideas @schriftgestalt ?

Thank you both and sorry for the inconvenience

**Comment by schriftgestalt** [comment]
The cutting edge version only very few changes other than that fix.

**Comment by mekkablue** [comment]
I can’t make it work with reasonable effort in the stable version. It works fine in the cutting edge.
