### ISSUE TITLE
OTvar player not working

### ISSUE THREAD

**Issue by arturschmal** [mekkablue/Glyphs-Scripts#166]
I'm not getting the OTvar Player to work in Version 2.6.2 (1268).
When I click the view in browser icon I'm getting this output:

```
Traceback (most recent call last):

  File "/Users/arturschmal/Library/Application Support/Glyphs/Scripts/vanilla/vanillaBase.py", line 220, in action_
    self.callback(sender)

  File "/Users/arturschmal/Library/Application Support/Glyphs/Scripts/Glyphs-Scripts/Interpolation/OTVar Player.py", line 301, in buildWeb
    os.system( terminalCommand )

UnicodeEncodeError: 'ascii' codec can't encode character u'\u2014' in position 31: ordinal not in range(128)
```

**Comment by mekkablue** [comment]
That happens when the file name you enter has non-ASCII letters like äçęúõ. Not sure I can circumvent this, but I will try. For now, use a file name with only regular A-Z, a-z, 0-9.

**Comment by mekkablue** [comment]
I am afraid I cannot fix it with the way I save files at the moment. Requires a bigger rewrite.

**Comment by arturschmal** [comment]
Sorry but the file has only ASCII characters...

**Comment by arturschmal** [comment]
The filename is Palindrome 02.glyphs

**Comment by mekkablue** [comment]
The path of the last OTVar Export?

**Comment by mekkablue** [comment]
The error message complains about an em dash in the path.

**Comment by arturschmal** [comment]
Right, there's a em dash in the path.
