### ISSUE TITLE
Set Hidden App Preferences: missing preferences

### ISSUE THREAD

**Issue by justanotherfoundry** [mekkablue/Glyphs-Scripts#170]
Seems like Set Hidden App Preferences has the same background/function as my own [Customize Defaults](https://github.com/justanotherfoundry/freemix-glyphsapp/blob/master/Customize%20Defaults.py) script but with a proper UI.

I was going to completely remove my script, as yours does it better, when I noticed that some preferences (those particularly interesting to me, see the comments over there) are missing: "GSCenterSelectionOnMasterSwitch", "TextModeNumbersThreshold", "showShadowPath"

Would it be possible to add them?

To me, it would make most sense to include rather more than fewer parameters in the Set Hidden App Preferences script, or practically all, as this is exactly the point of the tool: Being able to literally access all settings, not just a selection of those setting someone else finds important.

**Comment by mekkablue** [comment]
`TextModeNumbersThreshold` was already in the list, I added the two others

**Comment by justanotherfoundry** [comment]
Thanks!
