### ISSUE TITLE
Sync Components script error

### ISSUE THREAD

**Issue by laerm0** [mekkablue/Glyphs-Scripts#176]
Hi –

Looks like we have an issue in this script now.

```
Traceback (most recent call last):
  File "os.py", line 473, in __setitem__
    putenv(key, item)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0301' in position 69: ordinal not in range(128)
could not get AngledVBeam from saved preferences
could not get measureOverlaps from saved preferences
could not get showOffPathMeasures from saved preferences
Start
  File "/Users/stupakm/Documents/freelance/code_apps_etc/Glyphs gits/mekkablue Glyphs-Scripts/Components/Sync Components Across Masters.py", line 5
SyntaxError: Non-ASCII character '\xe2' in file /Users/stupakm/Documents/freelance/code_apps_etc/Glyphs gits/mekkablue Glyphs-Scripts/Components/Sync Components Across Masters.py on line 6, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
End
```

Let me know if you need help debugging. 👍

**Comment by laerm0** [comment]
I have the same issue in `Tabular Checker.py` it seems. I was able to fix the other script but fixing this one (deleting the line, retyping it, invisible glyphs on) didn't. 

```
Start
  File "/Users/stupakm/Documents/freelance/code_apps_etc/Glyphs gits/mekkablue Glyphs-Scripts/Spacing/Tabular Checker.py", line 33
SyntaxError: Non-ASCII character '\xe2' in file /Users/stupakm/Documents/freelance/code_apps_etc/Glyphs gits/mekkablue Glyphs-Scripts/Spacing/Tabular Checker.py on line 33, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
End
```

**Comment by laerm0** [comment]
[sorry, I apparently did not fill in the useful info in the issue name :) ]

**Comment by laerm0** [comment]
ping @mekkablue :)

**Comment by mekkablue** [comment]
I cannot reproduce. The scripts work fine for me. Which set-up (macOS and app versions) do you have?

**Comment by laerm0** [comment]
Hmm. Glyphs Version 2.6.4 (1280) and macOS 10.14.6. I just did a `git pull` on this repo and now it works fine. I swear I did that a couple weeks ago and it didn't work then… Sorry @mekkablue but thanks for checking in 😄

**Comment by mekkablue** [comment]
I made some bigger changes a couple of weeks ago. You must have been unlucky to pull right in the middle of them. Sorry for the inconvenience.

**Comment by laerm0** [comment]
Ah, no big deal. Glad it was an easy fix. 👍
