### ISSUE TITLE
Restore a couple of scripts

### ISSUE THREAD

**Issue by LibertyType** [mekkablue/Glyphs-Scripts#177]
macOS 10.13.6, G2.6.4 [1274]
Some time ago you decided for some reason to make some scripts obsolete. Two of them, _Select Same Color_ and _Select Same Layer Color,_ are ones I have used since you first provided them -- and they really are a time-saver. In fact I think _Select Same Color_ was a script I suggested and you provided it.

Today I found that Select Same Color no longer works. Please fix it and restore it to the collection. I cannot imagine any reason to consider it obsolete or not useful.

Macro Panel output:
Start
Traceback (most recent call last):
  File "Select Same Color.py", line 14, in <module>
    fontView = thisDoc.windowController().tabBarControl().viewControllers()[0].glyphsArrayController()
AttributeError: 'GSTabBarControl' object has no attribute 'viewControllers'
End

**Comment by weiweihuanghuang** [comment]
I use these scripts too.

**Comment by LibertyType** [comment]
Never mind; I just discovered I get the same functionality by setting up a Smart Filter. So I'm closing this one.
