### ISSUE TITLE
New tab with short segments returns error

### ISSUE THREAD

**Issue by tamirhassan** [mekkablue/Glyphs-Scripts#185]
Hi Rainer,

Just tried this out on two font files and got the following error:

Segments shorter than 5 units:
New Tab with Short Segments Error: 'NoneType' object has no attribute 'familyName'

I am happy to look into this issue myself, but won't get round to it until Tuesday.

**Comment by tamirhassan** [comment]
For a different font it hangs (endless loop)

**Comment by mekkablue** [comment]
Possibly due to changes in the API. Possible that it needs a rewrite.

**Comment by mekkablue** [comment]
Retiring the script. Functionality moved into Path Problem Finder.
