### ISSUE TITLE
Set Kerning Groups: Some random notes

### ISSUE THREAD

**Issue by Mark2Mark** [mekkablue/Glyphs-Scripts#190]
- **DZcaron** could have […, Z] instead of […, Zcaron]
- **Dzcaron** could have […, z] instead of […, zcaron]
- **dzcaron** could have […, z] instead of […, zcaron]
- **dzcaron**.sc could have […, z.sc] instead of […, zcaron.sc]
- **Eng** could have [H, …] instead of [Eng, …]
- **eng.sc** could have [h.sc, …] instead of [eng.sc, …]
- **Ohorn, Uhorn, ohorn, uhorn, ohorn.sc, uhorn.sc** could have an own right group?
- **Tcedilla** could* have [T, T] instead of [Tcommaaccent, Tcommaaccent] (when using commaaccent)
- **tcedilla** could* have [t, t] instead of [tcommaaccent, tcommaaccent] (when using commaaccent)
- **schwa** could have […, o*] instead of […, schwa]
- **kgreenlandic** could have [n, …] instead of [h, …]
- **eng** could have […, jdotless] instead of […, j] (as all other j glyphs have)
- **germandbls** could have [f, …] instead of [h, …]
- **fi** could have […, idotless] instead of […, i] (as all other i glyphs have)
- **.tf** numerals don’t need a group for each figure, they could all share one groups (e.g. "tabularfigure")
- **period, comma, colon** all got [period, period], but **semicolon** currently got [comma, period]

- **inferior, subs, numr, superior numbers** ALL all get "*.dnom" as groups. Is that on purpose? 

___
*) **edited**

**Comment by schriftgestalt** [comment]
**colon**/**semicolon** should not be in the period class.

**Comment by Mark2Mark** [comment]
Sure, fair enough. But the mentioned punctuations are still messy with "period" and or "comma", no visible logic there :)

**Comment by mekkablue** [comment]
germandbls is tricky. Depends a lot on the design.

**Comment by mekkablue** [comment]
> inferior, subs, numr, superior numbers ALL all get "*.dnom" as groups. Is that on purpose?

Yes. They are for kerning within themselves and with `fraction`. In rare cases:

* after a figure, but that would only ever apply to numerators, 
* after a lowercase letter, but that would only ever apply to a superior figure,
* after an uppercase letter, but that would only ever apply to an inferior figure.

So you can always use group kerning.

> .tf numerals don’t need a group for each figure, they could all share one groups (e.g. "tabularfigure")

Good question. My workflow was always to not give them any group, and then make sure .tf would not appear in the kern dict at all. How are you handling .tf in kerning?

**Comment by Mark2Mark** [comment]
> Yes. They are for kerning within themselves and with fraction. In rare cases:

I know, but I meant that the bottom numbers and the top numbers are in the same group, that cannot be correct, also not for the fraction kerning. Am I confusing sth here?

**Comment by Mark2Mark** [comment]
>  How are you handling .tf in kerning?

Mostly like you are. But I try to provide *every* glyph with a group. I think Georg once claimed that this is good to do, don’t know if he had .tf glyphs in mind for that as well. Basically I give them a group name and don’t give them kerning, though.
