### ISSUE TITLE
Type error in “Import Kerning from .fea File.py”?

### ISSUE THREAD

**Issue by lianghai** [mekkablue/Glyphs-Scripts#191]
Not sure if it’s only me. I keep hitting the issue below when I try to run the script.

<img width="532" alt="Screen Shot 2020-03-26 at 22 12 24" src="https://user-images.githubusercontent.com/343259/77658346-889b6000-6fb1-11ea-928c-e6cfc7fc9a3d.png">

Then I noticed `GetFile` will work fine if the third argument `["fea"]` is wrapped as `NSArray(["fea"])`. A PyObjC issue?

https://github.com/mekkablue/Glyphs-Scripts/blob/e8b0ec442d6e71470339e0851d989d81968aec97/Kerning/Import%20Kerning%20from%20.fea%20File.py#L82

macOS 10.15.3 (19D76).

**Comment by schriftgestalt** [comment]
That is a problem with in the python wrapper in Glyphs. Catalina changed the API again. I’ll fix it.
