### ISSUE TITLE
Path Problem Finder

### ISSUE THREAD

**Issue by Mark2Mark** [mekkablue/Glyphs-Scripts#192]
Traceback (most recent call last):
  File "Path Problem Finder.py", line 631, in PathProblemFinderMain
    u"Path Problem Finder found no issues, congratulations! Details in Macro Window." % countOfLayers,
UnboundLocalError: local variable 'countOfLayers' referenced before assignment

`countOfLayers = 0` is created in the `if` statement in line 601, but referenced in line 631 in the 
 `else`, too

**Comment by mekkablue** [comment]
Thanks, fixed.
