### ISSUE TITLE
Language Report false positive

### ISSUE THREAD

**Issue by alx3000** [mekkablue/Glyphs-Scripts#193]
I ran the script on a few fonts without a single cyrillic glyph, but it reports Ukrainian as one of supported languages. I know language support reporting is tricky, but this is a very clear case :)

**Comment by mekkablue** [comment]
This is about the romanization of Ukrainian, which is in widespread use and has its own rules.

**Comment by schriftgestalt** [comment]
Still a bit unexpected.

**Comment by mekkablue** [comment]
It actually says ‘Ukrainian (Latin transcription)’. I’ll leave it like this then. Not an issue.

**Comment by alx3000** [comment]
I see it says so in the script, but in the macro window I get this 

`215 languages supported:
[...] Tuvaluan, Tzotzil, Ukrainian, Uzbek, Venetian, [...]
`
That’s why it stood out to me.
