### ISSUE TITLE
pseudo random call — cycle first instances?

### ISSUE THREAD

**Issue by MattAppleton** [mekkablue/Glyphs-Scripts#197]
Hi there — first of all thanks for the amazing script resources!

I have a dead simple font test. A remix of Folio Bold where there are two extra letter 'a's. Your 'Create pseudorandom calt feature.py' script seems to work well to some degree, but I was curious to know if it would be possible to somehow make a script that ensured that consecutive words starting with the same letter stood a chance of now using the same glyph?

In this instance if I type 'art' and then 'app' it would be great if the two 'a's were different, if that makes sense?!

Many thanks!

<img width="1240" alt="Screenshot 2020-06-07 19 56 50" src="https://user-images.githubusercontent.com/6295710/83977552-3ce22c80-a8f9-11ea-9e1c-8965cb49711e.png">

**Comment by mekkablue** [comment]
You can add space to the cycle, which works but not everywhere, so it is risky (because not always the space _glyph_ is used for the word space, and an OT feature can only substitute a glyph). Consider switching to reversesub instead of sub or a backtrace where you sub x' y rather than x y'.
