### ISSUE TITLE
Vertical metrics manager inconsistency/bug?

### ISSUE THREAD

**Issue by MarcusSterz** [mekkablue/Glyphs-Scripts#199]
Used Vertical Metrics Manager, all ascender values identical in script but then looking different in info (screenshot, winAscent value 1 instead of 1060).
Override manually?

![Bildschirmfoto 2020-06-16 um 15 30 36](https://user-images.githubusercontent.com/51958720/84782960-f8394e00-afe8-11ea-8cae-b031157351b0.png)

**Comment by mekkablue** [comment]
What is your number and date locale in system preferences?
