### ISSUE TITLE
New Tab with Uneven Symmetric Kernings.py

### ISSUE THREAD

**Issue by franciscotorress** [mekkablue/Glyphs-Scripts#200]
getting an error when using this script.

don't know how to fix it

<img width="645" alt="Screenshot 2020-06-26 at 16 29 57" src="https://user-images.githubusercontent.com/38395134/85874482-99cf5500-b7ca-11ea-8ae3-1690d0f0d651.png">

**Comment by mekkablue** [comment]
There was no kerning group set for one of the glyphs involved.

**Comment by franciscotorress** [comment]
Got it! Thanks @mekkablue .
Still, would be nice if it could work without kerning groups.
