### ISSUE TITLE
TT Autoinstruct Selected Glyphs: anchors have “no Zone”

### ISSUE THREAD

**Issue by justanotherfoundry** [mekkablue/Glyphs-Scripts#204]
Ii seems TT Autoinstruct Selected Glyphs is supposed to give exactly the same results as right-click->Autohint in the TT tool? 

Then there’s a small problem: The anchor instructions have “no Zone” set whereas with right-click->Autohint they are set to auto, which is preferable. How could this be fixed? From what I can see in the Python code, the script simply calls autohintLayers_() so it seems Glyphs itself is to blame? @schriftgestalt

**Comment by mekkablue** [comment]
Good question. Not sure myself, will take a look in the source code.

**Comment by schriftgestalt** [comment]
The code is removing the stem on purpose. 
```
	for thisHint in thisLayer.hints:
		if thisHint.type == 3: # TT stem
			thisHint.setStem_(-1)
			returnValue = True
```
3 is not TT Stem but `TTANCHOR = 3`
And why would you remove the stem setting?

**Comment by mekkablue** [comment]
Confusion in my code then. That was probably supposed to be the stem, not the anchor. Rendering in AI is better if the stems are set to No Stem.

**Comment by justanotherfoundry** [comment]
Is it just the comment that is wrong, or the actual code? Does it need to be fixed?

**Comment by mekkablue** [comment]
There is a preference now you can set in _mekkablue > App > Set Hidden App Prefs:_ `com.mekkablue.ttAutoinstructSelectedGlyphs.alwaysUseNoStem`

I also used the predefined constant rather than the number value. I could not reproduce an issue where it set an _Anchor_ hint to _No Zone._ It should only ever set _Stem Hints_ to _No Stem_ (better rendering, especially in Adobe apps).

**Comment by justanotherfoundry** [comment]
In order to make the script set default stems (i.e. not call `setHintsToNoStem`), I tried:

- using _Set Hidden App Prefs_, changing `com.mekkablue.ttAutoinstructSelectedGlyphs.alwaysUseNoStem` from "1" to "0" (seemed intuitive) but this sets the _string_ "0" , which evaluates as `true` as the script is run. So, this doesn’t work.

- using _Set Hidden App Prefs_, clicking _Reset_. This deletes the preference and the script set it to 1 as it is run. So, this doesn’t work either.

- using _Set Hidden App Prefs_,  setting `com.mekkablue.ttAutoinstructSelectedGlyphs.alwaysUseNoStem` to an **empty string** (which eventually evaluates as `false`). Works!

That’s not easy to figure out, is it?

**Comment by justanotherfoundry** [comment]
On a related note, Glyphs sometimes creates invalid hints that have an `originNode` that is `None`.

I just updated one of my scripts to also delete these:
https://github.com/justanotherfoundry/freemix-glyphsapp/commit/c34b28ccc52ab548fd07c73d1cedbc42a464419a

@mekkablue  Maybe this tidy-up could be integrated into your script or, ideally, fixed directly in Glyphs?
@schriftgestalt This happens in Glyphs 2 and Glyphs 3.
