### ISSUE TITLE
Tunnify erratic - Glyphs 3, Big Sur

### ISSUE THREAD

**Issue by albertomalossi** [mekkablue/Glyphs-Scripts#205]
The tunnify script works as expected in Glyphs 2, but in 3 only acts in some glyphs. Strange because I don't think that my typeface has edge case curves or handles.
![Screen Shot 2020-11-20 at 10 39 18](https://user-images.githubusercontent.com/7223757/99784981-dd7d7f00-2b1c-11eb-9b54-dd55dd360f1e.png)

**Comment by etunni** [comment]
Hi, 
Tunnify stop working on G3 [3043]
Message at macro:
'<=' not supported between instances of 'float' and 'NoneType'
Traceback (most recent call last):
  File "Tunnify.py", line 54, in intersectionWithNSPoints
  File "Tunnify.py", line 89, in pointIsBetweenOtherPoints
TypeError: '<=' not supported between instances of 'float' and 'NoneType'
