### ISSUE TITLE
Find and Replace in Layer Name Bug

### ISSUE THREAD

**Issue by RosaWagner** [mekkablue/Glyphs-Scripts#206]
Just updated to Glyphs 3 :) It looks like this script doesn't work anymore to change a value of multiple intermediate layers.

**Comment by schriftgestalt** [comment]
The intermediate layers do not use the layer name to store its position. It uses a dedicated data structure. So it would need a different script.

**Comment by mekkablue** [comment]
Thinking of a Special Layers Manager. Let’s see.

**Comment by mekkablue** [comment]
New script: Brace Layer Manager.
