### ISSUE TITLE
ModuleNotFoundError: No module named 'PyObjCTools'

### ISSUE THREAD

**Issue by chrisjansky** [mekkablue/Glyphs-Scripts#209]
Running "Spacing > New tab will all figure combinations" yields the following error:

`
Traceback (most recent call last):
File "New Tab with all Figure Combinations.py", line 8
from PyObjCTools.AppHelper import callAfter
ModuleNotFoundError: No module named 'PyObjCTools'
`

MacOS Catalina (10.15.7). Using latest Glyphs 3 (3042) and today’s version of Glyphs-Scripts, all Python modules in Plugin Manager > Modules installed.

Any pointers please?

**Comment by schriftgestalt** [comment]
The Glyphs-Python module indeed misses that module. I have a look. 
@mekkablue do you remember why you used `callafter`?

**Comment by schriftgestalt** [comment]
for now, open the script, remove `from PyObjCTools.AppHelper import callAfter` and change the last line to: `Glyphs.currentDocument.windowController().addTabWithString_(text)`
