### ISSUE TITLE
Pixel: Reset Rotated and Mirrored Components yields error in G3

### ISSUE THREAD

**Issue by cdeliason** [mekkablue/Glyphs-Scripts#213]
On running, I get 'GSProxyShapes' object doesn't support item deletion
Appears to be the same issue solved in https://forum.glyphsapp.com/t/delete-all-paths-script/17053

**Comment by cdeliason** [comment]
Also looks like it needs "from Foundation import NSPoint" up top.

**Comment by schriftgestalt** [comment]
fixed it.
