### ISSUE TITLE
Kerncrash wrongly reports 0 collisions on G3

### ISSUE THREAD

**Issue by synthview** [mekkablue/Glyphs-Scripts#215]
Hi,
KernCrash wrongly reports zero collisions where it is impossible (I even have connecting glyphs that should be false positives).
On G2 and the same file (saved as G2 version) works.  With the same file in G3, KernCrash wrongly returns "no crashes"  :(

**Comment by synthview** [comment]
Gapfinder has the same issue

**Comment by mekkablue** [comment]
Fixed in KernCrasher
