### ISSUE TITLE
zero kerner error

### ISSUE THREAD

**Issue by RosaWagner** [mekkablue/Glyphs-Scripts#218]
In Glyphs 3

```
Zero Kerner Error: 'MGOrderedDictionary' object has no attribute 'startswith'
Traceback (most recent call last):
  File "Zero Kerner.py", line 172, in ZeroKernerMain
AttributeError: 'MGOrderedDictionary' object has no attribute 'startswith'
```

**Comment by mekkablue** [comment]
That is a bug in the API. All scripts that iterate through the kerning are affected. The Font.kerning dict is not properly wrapped as a Python dict.

Will file an issue in the app repository.

**Comment by mekkablue** [comment]
Update: you were right, API changes did require some changes. Should be fixed now.
