### ISSUE TITLE
Decompose components in background, infinite wheel

### ISSUE THREAD

**Issue by RosaWagner** [mekkablue/Glyphs-Scripts#220]
Glyphs 3
The wheel never stops turning when applying the script to an entire master.

**Comment by mekkablue** [comment]
Cannot in reproduce in 3075 on macOS 10.15.7. Can you upload a minimal testcase (1-glyph font perhaps) that triggers the issue?

I assume it has to do with a specific glyph in the font you are working on.

**Comment by mekkablue** [comment]
Rewrite of the script is imminent. Do you still have the issue?

**Comment by RosaWagner** [comment]
Didn't try it again sorry, but I do think that it was an issue related to the source file itself, probably intermediate masters, cause it worked with a different source.
