### ISSUE TITLE
Request: Delete detached corner/cap components

### ISSUE THREAD

**Issue by elenage** [mekkablue/Glyphs-Scripts#224]
If possible, it would be great to have a script that deletes all detached components on both base layer and background layer with "all masters" option.

**Comment by RafalBuchner** [comment]
@elenage a small question just to clarify: by detached components you mean those components that are not attached to the anchors – simply have automatic alignment disabled?

**Comment by schriftgestalt** [comment]
No, corner components.

**Comment by elenage** [comment]
For cases like this:
<img width="237" alt="Screenshot 2021-04-07 at 20 14 01" src="https://user-images.githubusercontent.com/20543172/113921407-e0cc8b00-97dd-11eb-82e9-2a8ca4901729.png">

**Comment by mekkablue** [comment]
It is the same corner components found by the script _Components > New Tab with Detached Corner Components._

**Comment by RafalBuchner** [comment]
@elenage  You could try this script:
[WIP_Remove Detached Corners.py.zip](https://github.com/mekkablue/Glyphs-Scripts/files/6296900/WIP_Remove.Detached.Corners.py.zip)

@mekkablue could you check this out and tell me if you want to append this script to your component scripts?

**Comment by mekkablue** [comment]
Yes, please add. (Also a line in README.md.) Thank you!

**Comment by elenage** [comment]
this one works perfectly, thank you!

E.
