### ISSUE TITLE
Error: Find and Replace Cap and Corner Components

### ISSUE THREAD

**Issue by elenage** [mekkablue/Glyphs-Scripts#225]
Macro Panel shows an error message
<img width="685" alt="Screenshot 2021-04-12 at 14 10 44" src="https://user-images.githubusercontent.com/20543172/114399610-06b8ad80-9b99-11eb-9d72-ec7f30658538.png">

**Comment by RafalBuchner** [comment]
@elenage Should work now. Please, try it out and tell me if it worked

**Comment by elenage** [comment]
Yes, thank you, seems to be working fine now.
