### ISSUE TITLE
Steal Kerning from InD cannot handle pairs with quoteright on the left side

### ISSUE THREAD

**Issue by mekkablue** [mekkablue/Glyphs-Scripts#226]
If a quoteright (’) is on the left side of the pair, the character cannot be parsed properly:

![image](https://user-images.githubusercontent.com/1103103/114559479-0f2de880-9c6c-11eb-9aab-bb3e860a5dfc.png)

…will result in:

```text
  ERROR: Could not set kerning for s:i.

could not convert string to float: 'gle right quotex -38'
  Offending line:
  single right quotex -38
Traceback (most recent call last):
  File "Steal kerning from InDesign.py", line 188
ValueError: could not convert string to float: 'gle right quotex -38'
```

**Comment by mekkablue** [comment]
It works if it is on the right side though (x’).

**Comment by RafalBuchner** [comment]
it is the behaviour of the apple script embedded into this code:
I don't understand why, but if you have `’x` it reads left glyph with full name (`double right quote`), and then it cannot be turned into Unicode value.

I could create a dictionary of exceptions like this, but I guess it would be counter-productive: every time we face such an issue, we would expand the dictionary. 

Unfortunately, I couldn't find the cause why AppleScript returns the full name. Do you want me to create this dictionary?

**Comment by RafalBuchner** [comment]
so far we are having this issue with `double right quote` and `single right quote`.

**Comment by mekkablue** [comment]
I implemented the dictionary. I think it works now.
