### ISSUE TITLE
Build circled glyphs - 'NoneType' object has no attribute 'bounds'

### ISSUE THREAD

**Issue by kosbarts** [mekkablue/Glyphs-Scripts#230]
Hi Eric

the script gives me this error in G2. 

Build Circled Glyphs Error: 'NoneType' object has no attribute 'bounds'
Traceback (most recent call last):
  File "Build Circled Glyphs.py", line 772, in BuildCircledGlyphsMain
    raise e
AttributeError: 'NoneType' object has no attribute 'bounds'

**Comment by mekkablue** [comment]
I think I fixed it. This can occur if you are trying to build circles for empty glyphs.
