### ISSUE TITLE
Build Circled Glyphs fails in Glyphs 3

### ISSUE THREAD

**Issue by jpt** [mekkablue/Glyphs-Scripts#235]
I started work on this in #234 but then I saw that maybe `NSKVONotifying_GSFontMaster` [isn't supported in Glyphs 3](https://forum.glyphsapp.com/t/insert-brace-layers-for-component-rotation-script/17589/2), is that the case @mekkablue?

**Comment by schriftgestalt** [comment]
`NSKVONotifying_GSFontMaster` is the name that the python is using. It is just `GSFontMaster`. 
And it is still a central part of the data structure. Only the API how you access the metrics and axes coordinates has changed.

**Comment by jpt** [comment]
got it. there were a few other issues, all updated in #234 if you can verify and merge. thanks for the help 😄
