### ISSUE TITLE
Remove Components does not work

### ISSUE THREAD

**Issue by lettersoup** [mekkablue/Glyphs-Scripts#236]
Remove Components for selected glyphs does not work in Glyphs 2 and Glyphs 3. Would you please check it.

**Comment by mekkablue** [comment]
It does for me in 3.0.3 (3088):

![image](https://user-images.githubusercontent.com/1103103/122751186-54cbea80-d287-11eb-8d0c-210424707ff0.png)

Can you describe steps for reproducing the issue?

**Comment by lettersoup** [comment]
I´m selecting:
<img width="728" alt="Bildschirmfoto 2021-06-21 um 13 01 32" src="https://user-images.githubusercontent.com/6229652/122752167-e3913500-d290-11eb-80ee-16e5474aec69.png">
and would like to remove the combs.

**Comment by mekkablue** [comment]
You want to clear the glyphs? Better use _Edit > Clear._

The script is just for deleting a specific component. The one you specify in the UI. Will think about introducing wildcards.

Sorry for late reply.
