### ISSUE TITLE
Bug? New tab with glyphs not reaching into Zones list SC with zone as having no top zone

### ISSUE THREAD

**Issue by schriftlabor-miriam** [mekkablue/Glyphs-Scripts#238]
version 3091

**Comment by mekkablue** [comment]
Thx for reporting, will investigate. The API is more complicated in G3.

@RafalBuchner: in G3, make sure to compare with `Layer.metrics`, script may need a (partial) rewrite.

**Comment by RafalBuchner** [comment]
cannot reproduce
