### ISSUE TITLE
Is E with breve character obsolete? (Language Report)

### ISSUE THREAD

**Issue by alirizaesin** [mekkablue/Glyphs-Scripts#242]
My question is not about the mechanism —it works very well for me— but about the content of Test/Language Report.

If we should add “E with breve” character(s) for to support Kurdish or not, as the report suggest? I would gladly do that BTW, because, except for the advantages of supporting one more language, it’s ridiculously easy on Glyphs.

I came cross this on a font update changelog (https://typodermicfonts.com/wp-content/uploads/2021/07/typodermic-changelog-2021-07-05.pdf) document, as “deprecated and obsolete character” but I can’t confirm myself. I thought it’s worth to your attention.

**Comment by mekkablue** [comment]
You are right, that is a mistake, it should be E with circumflex.
