### ISSUE TITLE
Straight stem cruncher script crash

### ISSUE THREAD

**Issue by drawcard** [mekkablue/Glyphs-Scripts#244]
This happened when I clicked the update button, next to the stem value field (Glyphs 3.0.4)

Traceback (most recent call last):

File “/Users/drawcard-m1/Library/Application Support/Glyphs 3/Scripts/vanilla/vanillaBase.py”, line 506, in action_
self.callback(sender)

File “/Users/drawcard-m1/Library/Application Support/Glyphs 3/Repositories/mekkablue/Paths/Straight Stem Cruncher.py”, line 156, in update
for stemSet in (master.horizontalStems, master.verticalStems):

AttributeError: ‘NSKVONotifying_GSFontMaster’ object has no attribute ‘horizontalStems’

**Comment by mekkablue** [comment]
Need an update for Glyphs 3.

@RafalBuchner: Can you ad G3-style code with `GSFontMaster.stems` instead?

**Comment by RafalBuchner** [comment]
Please @drawcard, update the scripts and check out if it works for you. I would thankful if you could report the result.
If there will be still a problem, please, send screenshot of your `Straight stem cruncher` settings.

**Comment by drawcard** [comment]
Looks like it works, thanks for the quick fix :)
