### ISSUE TITLE
"Propagate Corner Components to Other Masters" to work with segments too? 

### ISSUE THREAD

**Issue by Malou1** [mekkablue/Glyphs-Scripts#254]
That would be amazzzziiing :-)

**Comment by mekkablue** [comment]
You mean segment components? I can try.

**Comment by Malou1** [comment]
Yes! segment components! Would be really amazing!
Maybe one day a "sync manager" (Components / corners / caps / Segments / Anchors…) or as part of "copy layer to layer"? Just thinking out loud here ;-)

**Comment by mekkablue** [comment]
Sorry it took so long. Was easier than I thought.

**Comment by Malou1** [comment]
Merci!!!!
