### ISSUE TITLE
Readme gives installation instructions for Glyphs 2, not 3

### ISSUE THREAD

**Issue by arrowtype** [mekkablue/Glyphs-Scripts#257]
The readme directs users to install scripts in `~/Library/Application Support/Glyphs/Scripts/`, which I think (assume?) is just used for Glyphs 2. It may be useful to direct them to `~/Library/Application Support/Glyphs 3/Scripts`, or to mention if scripts in the `Glyphs/Scripts/` folder are picked up by Glyphs 3.

**Comment by mekkablue** [comment]
No, it starts with the installation instructions for Glyphs 3 (big headline). The remaining instructions, under ‘Glyphs 2’, are for Glyphs 2. I added ‘for Glyphs 2’ to all sub headlines to make it clearer. HTH.

**Comment by arrowtype** [comment]
Sounds good. Cheers!
