### ISSUE TITLE
Error: Monospace Checker.py

### ISSUE THREAD

**Issue by schriftlabor-miriam** [mekkablue/Glyphs-Scripts#277]
Traceback (most recent call last):
  File "Monospace Checker.py", line 8
    import vanilla
  File "__init__.py", line 1
    from vanilla.vanillaBase import VanillaBaseObject, VanillaBaseControl, VanillaError
  File "vanillaBase.py", line 2
    from packaging.version import Version
ModuleNotFoundError: No module named 'packaging'

**Comment by schriftgestalt** [comment]
Please uninstall and reinstall "vanilla" in Window > Plugin Manager > Modules, and restart the app.
