### ISSUE TITLE
Componenr Mover - Script / G3-Lates cutting edge / MacOs Catalina 10.15.7

### ISSUE THREAD

**Issue by etunni** [mekkablue/Glyphs-Scripts#280]
**This is the issue at macro window**

Traceback (most recent call last):
  File "Component Mover.py", line 240
    ComponentMover()
  File "Component Mover.py", line 40, in __init__
    self.w.changeAttribute = vanilla.PopUpButton( (inset+55, linePos-1, -inset-25, 20), self.defaultSettings+self.availableAttributes(), sizeStyle='small', callback=self.SavePreferences )
  File "Component Mover.py", line 136, in availableAttributes
    if searchString=="" or (searchString!="" and searchString in component.componentName):
TypeError: 'in <string>' requires string as left operand, not NoneType

**Comment by mekkablue** [comment]
Should work again?
