### ISSUE TITLE
OTVar player stopped working

### ISSUE THREAD

**Issue by philippnurullin** [mekkablue/Glyphs-Scripts#292]
Glyphs version: 3.2 (3181)
OS: Mac OS Ventura 13.2.1

**Comment by mekkablue** [comment]
Works for me. Can you share the error message?

**Comment by philippnurullin** [comment]
Unfortunately, there seems to be no error message at all.
Downgraded to 3.1.2 (3151). This issue is still persistent.

I also have two versions of Glyphs installed. The other is 2.6.10 (1364)
It does not see the Python installed.

But Python is installed indeed. It is v 3.11.

**Comment by schriftgestalt** [comment]
For Glyphs 2, read this: https://glyphsapp.com/news/glyphs-2-on-monterey

**Comment by philippnurullin** [comment]
The instruction fixes the issue with Glyphs 2, thanks.
