### ISSUE TITLE
It just doesn't do anything in apple M1

### ISSUE THREAD

**Issue by legyszike** [mekkablue/Glyphs-Scripts#296]
I would like to generate instances from my masters, but every time I go to insert instances, it just does nothing. I have apple m1, what should i do with this issue?

**Comment by schriftgestalt** [comment]
Do you get any error messages in the Macro Window?

**Comment by legyszike** [comment]
No, nothing happens, like I haven't done anything.

**Comment by mekkablue** [comment]
This has nothing to do with M1. Follow the instructions in the tutorial: https://glyphsapp.com/learn/extending-glyphs
