### ISSUE TITLE
Brace & Bracket Manager: Issue when glyph without target layer included in selection

### ISSUE THREAD

**Issue by clauseggers** [mekkablue/Glyphs-Scripts#308]
If I select a handful of glyphs to make a search-and-replace using your `Brace and Bracket Manager` then I get this error if one of the glyphs does not contain the bracket layer that is targeted.

I then have to go through each glyph manually.

```
Brace and Bracket Manager Report for Playfair
/Users/claus/Git/clauseggers/Playfair/sources/Playfair-2_1-Roman.glyphs

🔢 Attempting Width: 97.0 → 99.0
  Processing g...
Brace and Bracket Manager Error: 'a02'
Traceback (most recent call last):
  File "Brace Layer Manager.py", line 236, in BraceLayerManagerMain
    axisLimits = axisRules[axisID]
  File "_convenience_mapping.py", line 18, in __getitem__objectForKey_
    return container_unwrap(res, KeyError, key)
  File "_convenience.py", line 113, in container_unwrap
    raise exc_type(*exc_args)
KeyError: 'a02'
```

**Comment by clauseggers** [comment]
In this case it really broke (as far as I can see), even in a glyph that has the correct layer.

<img width="1059" alt="Screenshot 2023-07-03 at 13 26 34" src="https://github.com/mekkablue/Glyphs-Scripts/assets/868987/bf7b3880-26c4-47e5-a1c3-43b39449c3de">

**Comment by mekkablue** [comment]
Probably the wrong axis selected. I’ll catch the error and put out a proper warning message in Macro Panel.

**Comment by clauseggers** [comment]
I did keep the B&B window open while I moved from glyph to glyph, maybe that confused the script?
