### ISSUE TITLE
Instance Cooker renames `Normal` to `Regular`

### ISSUE THREAD

**Issue by clauseggers** [mekkablue/Glyphs-Scripts#313]
I have this set:

```
#Weight:wght
100:UltraThin
200:Thin
300:Light
400:Normal*
500:Medium
600:SemiBold
700:Bold
800:ExtraBold
900:Black
```

After I have run it, the `Normal` is renamed to `Regular` in the Style Linking:

<img width="992" alt="Screenshot 2023-08-01 at 12 33 03" src="https://github.com/mekkablue/Glyphs-Scripts/assets/868987/487be934-1b94-4b7d-b8b6-8c6ea4e4f07b">

**Comment by clauseggers** [comment]
I found part of the issue, and it was that I had set my Italic axis like you did in the description file. You wrote 
```
#Italic:ital
1:Regular*
```
so I wrote in my Italic
```
#Italic:ital
1:Italic*
```
The * borks everything. Remove it and the cooker works for Italic.

However, there is still an issue with `Regular` vs. `Normal`. I use `Normal` in the project, but the script can’t figure that out and replaces occurrences with `Regular`.

**Comment by mekkablue** [comment]
1. The asterisk `*` is for marking the elidable name, usually the word _Regular._ Elidable means that it gets dropped as soon as it is combined with another word, e.g. _Condensed Regular_ would turn into just _Condensed._ I cannot think of a context where _Italic_ would be elidable.

2. `Normal*` works for me as expected. I had this recipe:

```
#Width:wdth
75|3:Condensed
100|5:Normal*
150|7:Extended

#Weight:wght
30>100:Thin
50>200:Extralight
70>300:Light
85>400:Normal*
105>500:Medium
120>600:Semibold
145>700:Bold
175>800:Extrabold
190>900:Black

#Italic:ital
0:Normal*
1:Italic
```

And the instances generated were as follows (**bold**=elided weight name, *italic*=elided width name):

Condensed Thin
Condensed Thin Italic
Condensed Extralight
Condensed Extralight Italic
Condensed Light
Condensed Light Italic
**Condensed**
Condensed Italic
Condensed Medium
Condensed Medium Italic
Condensed Semibold
Condensed Semibold Italic
Condensed Bold
Condensed Bold Italic
Condensed Extrabold
Condensed Extrabold Italic
Condensed Black
Condensed Black Italic
_Thin
Thin Italic
Extralight
Extralight Italic
Light
Light Italic
**Normal**
Italic
Medium
Medium Italic
Semibold
Semibold Italic
Bold
Bold Italic
Extrabold
Extrabold Italic
Black
Black Italic_
Extended Thin
Extended Thin Italic
Extended Extralight
Extended Extralight Italic
Extended Light
Extended Light Italic
**Extended**
Extended Italic
Extended Medium
Extended Medium Italic
Extended Semibold
Extended Semibold Italic
Extended Bold
Extended Bold Italic
Extended Extrabold
Extended Extrabold Italic
Extended Black
Extended Black Italic

**Comment by clauseggers** [comment]
The issue persists. This recipe
```
#Weight:wght
100>100:UltraThin
145>200:Thin
200>300:Light
265>400:Normal*
350>500:Medium
450>600:SemiBold
570>700:Bold
720>800:ExtraBold
900>900:Black

#Italic:ital
0:Normal*
```
Yields this error:
<img width="1040" alt="Screenshot 2023-08-10 at 13 51 10" src="https://github.com/mekkablue/Glyphs-Scripts/assets/868987/068895ff-6cf9-434a-872c-18721bc5f737">

Are we on the same page here?

I don’t understand this
```
#Italic:ital
0:Normal*
1:Italic
```
Why is there both declarations under both the upright and italic? Is it an example where I delete one? It produces empty instances of the non-extant style in each file if I declare both. Is it for the lunatics who has interpolating Italic and Roman in the same file?

Finally, the `axis location` custom parameter: Why is it created since it is the same as the weight class? Must it be there?

**Comment by clauseggers** [comment]
Just had a go on at the Italic. I used this:
```
#Weight:wght
100>100:UltraThin
145>200:Thin
200>300:Light
265>400:Italic*
350>500:Medium
450>600:SemiBold
570>700:Bold
720>800:ExtraBold
900>900:Black

#Italic:ital
1:Italic*
```

But got this:
<img width="1150" alt="Screenshot 2023-08-10 at 14 02 45" src="https://github.com/mekkablue/Glyphs-Scripts/assets/868987/ac34251a-a5eb-4d23-a762-c489f13ebd47">
<img width="1017" alt="Screenshot 2023-08-10 at 14 03 24" src="https://github.com/mekkablue/Glyphs-Scripts/assets/868987/ba77bc63-c2ee-4474-96f7-f6089ce7dd15">
