### ISSUE TITLE
`Find and Replace in Anchor Names` confuses Glyphs into thinking there layers are incompatible

### ISSUE THREAD

**Issue by clauseggers** [mekkablue/Glyphs-Scripts#315]
For some reason running the `Find and Replace in Anchor Names` confuses Glyphs into thinking there are layers witch are incompatible due to the existence of anchors with the old name. In fact the layers are compatible, and the script renamed it all perfectly, but Glyphs still sees the old anchors in *some* of the layers. Restarting Glyphs fixed it.

**Comment by mekkablue** [comment]
The compatibility indicators not updating has been an issue particularly in the most recent build(s). Applying pretty much any action on these layers will trigger an update, like moving a node or rounding coordinates.
