### ISSUE TITLE
`Remove Nodes and Try to Keep Shape` status?

### ISSUE THREAD

**Issue by danielgamage** [mekkablue/Glyphs-Scripts#317]
Just a question: I found `Remove Nodes and Try to Keep Shape` super helpful! I'm wondering if [it being removed](https://github.com/mekkablue/Glyphs-Scripts/commit/efd8e8dd93049f8f3dfb5df2e086bfe02d16c36d) means the functionality has made it into an unreleased Glyphs 3.2 version in core, or if there's another script that you'd prefer people use instead?

I tried just using the `delete` key on multiple nodes in the latest 3.2beta (3231), but it seems to still result in the usual behavior:

<img width="755" alt="Screenshot 2023-12-21 at 13 18 39" src="https://github.com/mekkablue/Glyphs-Scripts/assets/1642599/a4dd1266-d4af-4a85-be0d-b381e31fff8c">

_start_

<img width="755" alt="Screenshot 2023-12-21 at 13 18 45" src="https://github.com/mekkablue/Glyphs-Scripts/assets/1642599/ddee484c-866c-4aaf-991c-231f26673159">

_`delete` key_

<img width="755" alt="Screenshot 2023-12-21 at 13 18 50" src="https://github.com/mekkablue/Glyphs-Scripts/assets/1642599/5719b68f-9718-4c42-afce-fd181b929b3f">

_`Remove Nodes and Try to Keep Shape`_

Appreciate any info! :)

**Comment by mekkablue** [comment]
Replaced by the _Magic Remover_ plug-in.
