### ISSUE TITLE
`Sync Components Across Masters` does not respect alternate layers

### ISSUE THREAD

**Issue by clauseggers** [mekkablue/Glyphs-Scripts#325]
When I run `Sync Components Across Masters` it does not respect the alternate layers (Bracket layers). It simply duplicates the content of the layer you are currently on to all layers.

Expected behaviour: The script should only copy components to layers of the same specification, but for all the layers. Example: Sync the normal layer, but separately sync the components of alternate layers, eg. `[oz>400]`

**Comment by mekkablue** [comment]
Should work now.
