### ISSUE TITLE
No module named 'mekkablue'

### ISSUE THREAD

**Issue by weiweihuanghuang** [mekkablue/Glyphs-Scripts#330]
```
Traceback (most recent call last):
  File "Copy Layer to Layer.py", line 10
    from mekkablue import mekkaObject
ModuleNotFoundError: No module named 'mekkablue'
```
Updated my scripts and now I get this error

**Comment by weiweihuanghuang** [comment]
Oh I see it's because I changed the symlink to '_Mekkablue' so that it would appear in the menu first. Is ther any work around here without editing all the scripts?

**Comment by weiweihuanghuang** [comment]
No I only renamed the alias:

<img width="732" alt="Screen Shot 2024-03-25 at 12 20 35 pm" src="https://github.com/mekkablue/Glyphs-Scripts/assets/1271897/b3544d19-f0b4-4bdc-b07d-eeb70922b5d8">
<img width="708" alt="Screen Shot 2024-03-25 at 12 20 26 pm" src="https://github.com/mekkablue/Glyphs-Scripts/assets/1271897/2dd879a8-c902-4e6d-b9f3-830f0dd6c2a8">

Which is strange right

**Comment by schriftgestalt** [comment]
The alias is what python sees. So that determines the module name. The name you are linking to can be change.
