### ISSUE TITLE
Avoid live print() reporting while script is running for faster processing

### ISSUE THREAD

**Issue by weiweihuanghuang** [mekkablue/Glyphs-Scripts#331]
I've noticed some scripts take a long time to run when processing, for example, [Kink Finder](https://github.com/mekkablue/Glyphs-Scripts/blob/master/Interpolation/KinkFinder.py), [Copy Layer to Layer](https://github.com/mekkablue/Glyphs-Scripts/blob/master/Interpolation/Copy%20Layer%20to%20Layer.py) – basically any script that has to process a lot of objects one by one and report each step.

It runs very slowly because it's constantly outputting to the macro panel. I've tested removing the print() reporting and the difference is sometimes several minutes vs a few seconds with and without the live reporting. I'd suggest perhaps writing to a string and printing the whole string either at the end or when the script breaks.

**Comment by mekkablue** [comment]
Which app build?

**Comment by schriftgestalt** [comment]
A `print()` enters a different run loop to let the UI update and redraw the macro window. That is rather slow. So it shouldn’t be done in a tight look.

**Comment by weiweihuanghuang** [comment]
Steal Kerning Groups, Steal Metrics also very slow because of this.

**Comment by mekkablue** [comment]
Should be OK for most scripts. If you find a slow script, please open a separate issue for that script.
