### ISSUE TITLE
Anchor Mover doesn’t work for small-caps

### ISSUE THREAD

**Issue by clauseggers** [mekkablue/Glyphs-Scripts#334]
For some unknown reason the Anchor Mover doesn’t work for small-caps. I have small-caps set in the font info vertical metrics.

**Comment by clauseggers** [comment]
Today I got some error loggin at least
```
Processing 1 glyph...

🔠 i.smcp
ERROR: Failed to move anchor in i.smcp.
unsupported operand type(s) for /: 'NoneType' and 'int'
Traceback (most recent call last):
  File "Anchor Mover.py", line 214, in MoveCallback
    yMove = eval(evalCodeV) + vertical_change
            ^^^^^^^^^^^^^^^
  File "<macro panel>", line 1
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

ERROR: Failed to move anchor in i.smcp.
unsupported operand type(s) for /: 'NoneType' and 'int'
Traceback (most recent call last):
  File "Anchor Mover.py", line 214, in MoveCallback
    yMove = eval(evalCodeV) + vertical_change
            ^^^^^^^^^^^^^^^
  File "<macro panel>", line 1
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

ERROR: Failed to move anchor in i.smcp.
unsupported operand type(s) for /: 'NoneType' and 'int'
Traceback (most recent call last):
  File "Anchor Mover.py", line 214, in MoveCallback
    yMove = eval(evalCodeV) + vertical_change
            ^^^^^^^^^^^^^^^
  File "<macro panel>", line 1
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

ERROR: Failed to move anchor in i.smcp.
unsupported operand type(s) for /: 'NoneType' and 'int'
Traceback (most recent call last):
  File "Anchor Mover.py", line 214, in MoveCallback
    yMove = eval(evalCodeV) + vertical_change
            ^^^^^^^^^^^^^^^
  File "<macro panel>", line 1
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

ERROR: Failed to move anchor in i.smcp.
unsupported operand type(s) for /: 'NoneType' and 'int'
Traceback (most recent call last):
  File "Anchor Mover.py", line 214, in MoveCallback
    yMove = eval(evalCodeV) + vertical_change
            ^^^^^^^^^^^^^^^
  File "<macro panel>", line 1
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

ERROR: Failed to move anchor in i.smcp.
unsupported operand type(s) for /: 'NoneType' and 'int'
Traceback (most recent call last):
  File "Anchor Mover.py", line 214, in MoveCallback
    yMove = eval(evalCodeV) + vertical_change
            ^^^^^^^^^^^^^^^
  File "<macro panel>", line 1
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

Done.
```

**Comment by clauseggers** [comment]
Your code for deriving small-caps metrics is kaput. I have the value set in each master, and using other metrics in the script works fine.

<img width="285" alt="Screenshot 2024-04-19 at 12 26 34" src="https://github.com/mekkablue/Glyphs-Scripts/assets/868987/56057e6c-1b35-4d99-a78f-847a2b72bd5f">

**Comment by clauseggers** [comment]
Caught it on video. I’ve attached the video and the state of the Glyphs file.

https://github.com/mekkablue/Glyphs-Scripts/assets/868987/41d7b760-0926-412a-8553-a913a5afc64d

[Playfair-2_2-Roman 9.glyphs.zip](https://github.com/mekkablue/Glyphs-Scripts/files/15127644/Playfair-2_2-Roman.9.glyphs.zip)

**Comment by clauseggers** [comment]
I think I just spotted the reason. The glyph in question is not named `*.smcp` and this ‘breaks’ your script. It works fine in glyphs named `*.smcp`. I’ll rename my components.

**Comment by clauseggers** [comment]
It gets stranger. The Italic component glyph *does* have the small-caps metrics displayed in the edit window, whereas the Roman for some unknown reason does not.
<img width="2253" alt="Screenshot 2024-04-26 at 10 59 21" src="https://github.com/mekkablue/Glyphs-Scripts/assets/868987/fe6c9e97-5df2-4e29-8313-ad659fca4cf8">
<img width="2018" alt="Screenshot 2024-04-26 at 10 59 52" src="https://github.com/mekkablue/Glyphs-Scripts/assets/868987/1c72a5e6-7c12-4ad5-b4a5-cba26f3aa821">

**Comment by schriftgestalt** [comment]
Can you click on the "Smallcaps" and screenshot the resulting dialog?

**Comment by clauseggers** [comment]
Oh, that is new to me. They are different, but what should the correct settings be?

<img width="1251" alt="Screenshot 2024-04-26 at 11 22 54" src="https://github.com/mekkablue/Glyphs-Scripts/assets/868987/73d4ee91-bbca-4328-b0e8-767a649b159f">
<img width="1251" alt="Screenshot 2024-04-26 at 11 22 37" src="https://github.com/mekkablue/Glyphs-Scripts/assets/868987/6ae3141e-1874-408e-a1be-c486b0d5206a">

**Comment by mekkablue** [comment]
I removed the small cap option from the code for now, it is not compatible with G3+. Will need to rewrite with a metrics scan of the file.
