### ISSUE TITLE
Replace Components script should be wider

### ISSUE THREAD

**Issue by clauseggers** [mekkablue/Glyphs-Scripts#335]
I can’t see the names of the components because the fields are too narrow. In this window I have expanded the window as wide as it will go, which is insufficient and asymmetrical.

I suggest putting the `Replace` and `by` drop-downs in each their own layer, and allow the user to make the window as wide as they want.

<img width="662" alt="Screenshot 2024-04-20 at 11 10 39" src="https://github.com/mekkablue/Glyphs-Scripts/assets/868987/cb9d2211-9bd6-4812-aac6-654ea51c09b8">

**Comment by schriftgestalt** [comment]
Or like this: <img width="416" alt="Screen Shot 2024-04-20 at 17 59 17" src="https://github.com/mekkablue/Glyphs-Scripts/assets/174660/a7280c53-fab6-4c91-8a5d-b12d442ce0df">

**Comment by clauseggers** [comment]
Exactly.
