### ISSUE TITLE
Anchor Mover can move anchor

### ISSUE THREAD

**Issue by clauseggers** [mekkablue/Glyphs-Scripts#339]
Very weird. The anchor mover script can’t move the chosen anchor in one of the layers. The rest or the layers are working.

https://github.com/mekkablue/Glyphs-Scripts/assets/868987/4eef6b5a-11de-4c3e-92e9-c99a333c3f40

After manually moving the anchor a bit, then re-running the script it worked.

**Comment by mekkablue** [comment]
Cannot reproduce. Anchor Mover needs a colossal rewrite sometime soon, though.

**Comment by mekkablue** [comment]
Made some changes that probably caught this edge case as well.
