### ISSUE TITLE
Variation Interpolation is not working in Glyphs 2.0.0 (688)

### ISSUE THREAD

**Issue by Omnibus-Type** [mekkablue/Glyphs-Scripts#34]
Seems like variation interpolation is not working in Glyphs 2.0.0 (688). It works in Glyphs 1.4.5 (614)

**Comment by Omnibus-Type** [comment]
Also, could the script interpolate anchors too?

**Comment by mekkablue** [comment]
I cannot reproduce the "not working". It works as expected in Version 2.0.0 (688) for me. Is there anything in the Macro window?

**Comment by mekkablue** [comment]
Now interpolates anchors too. Tested in 2.0.0 (688).
