### ISSUE TITLE
Adjust Kerning in Master.py does not apply for RTL Kerning

### ISSUE THREAD

**Issue by danielgrumer** [mekkablue/Glyphs-Scripts#340]
Hey Rainer!
We tried to use `Adjust Kerning in Master.py` but noticed that it doesn't apply for RTL kerning :(
Is there a way to use the script with RTL kerning?

Thanks! Daniel

**Comment by mekkablue** [comment]
Added it, thanks.

**Comment by arbsh** [comment]
Yes I can do everything

في الجمعة، ٢٦ يوليو ٢٠٢٤ ١٠:٣٩ م Rainer Erich Scheichelbauer <
***@***.***> كتب:
