### ISSUE TITLE
Adjust Kerning in Master.py error

### ISSUE THREAD

**Issue by designingdesign** [mekkablue/Glyphs-Scripts#37]
Cutting edge. Glyphs 2 on 10.9.5
This script crashes my Glyphs App. Works in Glyphs 2 though?

I think it's something to do with this:

```python
import vanilla
import GlyphsApp

Font = Glyphs.font
Master = Font.selectedFontMaster
MasterID = Master.id
MasterKernDict = Font.kerning[ MasterID ]

for leftGlyphID in MasterKernDict.keys():
	print leftGlyphID
```

Works in Glyphs 1,
but returns this error in Glyphs 2:
```
Traceback (most recent call last):
  File "<string>", line 9, in <module>
TypeError: 'list' object is not callable
```

**Comment by mekkablue** [comment]
Until I get to fix it and upload it, replace keys() with keys. Unfortunately my github upload is broken currently and it may take some time.

**Comment by mekkablue** [comment]
In the next update of the Glyphs 2 beta, keys() will work again (with parentheses). So I will leave it like it is.
