### ISSUE TITLE
Copy Layer to Layer issue

### ISSUE THREAD

**Issue by MajusCorp** [mekkablue/Glyphs-Scripts#44]
G2 [699] OS X 10.10.2

Trying to use the script "Copy Layer to Layer", I get this return:
Processing Gheupturn-cy
object of type 'NoneType' has no len()

Does this script need updating for G2?

**Comment by mekkablue** [comment]
Can you send me the glyph where this is happening? The script works fine for me.

**Comment by MajusCorp** [comment]
HI Rainer:

Sure, attached.

I want to copy all of the Cyrillic glyphs colored Brown from the Light 
layer to the Bold layer.

Thanks,

George Thomas

**Comment by mekkablue** [comment]
Where did you attach it? Perhaps send an e-mail to res (at) glyphsapp (dot) com.
