### ISSUE TITLE
Distribute Nodes horizontally shifts bounding points too much

### ISSUE THREAD

**Issue by flopflip21** [mekkablue/Glyphs-Scripts#45]
Before
![screen shot 2015-03-04 at 1 49 25 pm](https://cloud.githubusercontent.com/assets/11042561/6483789/4f4625c2-c275-11e4-906b-a8aa10018807.png)

After
![screen shot 2015-03-04 at 1 49 30 pm](https://cloud.githubusercontent.com/assets/11042561/6483790/50d53626-c275-11e4-8ccd-329f6bfd324e.png)

**Comment by mekkablue** [comment]
Should be fixed.
