### ISSUE TITLE
Select same color

### ISSUE THREAD

**Issue by guidoferreyra** [mekkablue/Glyphs-Scripts#47]
Hi! In Glyphs2 when the selection is performed by the script and I hit double click to open them in edit view, it only opens one glyph, the clicked one.

**Comment by mekkablue** [comment]
Not much the script can do about this. Experiment with your double click speed in your Accessibility preferences. Or simply type Cmd-T instead of double clicking.

**Comment by guidoferreyra** [comment]
It only happens on G2, cmd-T doesn't work, maybe only happens in my computer.
Best regards.

**Comment by mekkablue** [comment]
I could just reproduce it. Not sure yet what’s happening.

**Comment by mekkablue** [comment]
I could not reproduce it anymore in the latest betas.
