### ISSUE TITLE
Steal kernings error 

### ISSUE THREAD

**Issue by Joecoco** [mekkablue/Glyphs-Scripts#51]
Can't select different masters in the box so it is not possible copying kernings from a master to another. Few month ago it worked so it may comes from updates? Thanks for your help ;)

![capture d ecran 2015-05-03 a 18 01 55](https://cloud.githubusercontent.com/assets/12222436/7445748/d2ced172-f1bf-11e4-971f-29e4818d0dc9.png)

**Comment by schriftgestalt** [comment]
Kerning classes are not master based but glyph based. So you need to open two fonts to copy the values from one font to the other.

**Comment by weiweihuanghuang** [comment]
You can use this script to copy kerning from class/glyph to class/glyph https://github.com/Tosche/Glyphs-Scripts/blob/master/Metrics%20%26%20Kerning/Copy%20Kerning%20Pairs.py

**Comment by mekkablue** [comment]
The script does not (and never did) copy kerning. It copies kerning pairs from one font to another.

To copy kerning, open *Window > Kerning*, select all, copy, switch fonts, paste.

**Comment by Joecoco** [comment]
I wouldn’t thought it was so simple… the first time I would have tried font to font. Nice ! Thank you !
