### ISSUE TITLE
Create pseudorandom calt feature from ssXX glyphs ERROR

### ISSUE THREAD

**Issue by POXtheMusician** [mekkablue/Glyphs-Scripts#52]
Hello,

While trying to use the script nothing happens, the app prints this in the macro panel:

`Start
  File "Create pseudorandom calt feature.py", line 113
    print "" create_otclass( classname = className, classglyphs = classGlyphs )
                          ^
SyntaxError: invalid syntax
End`

I also tried to delete "" but then the error looks like this:

`Start
Traceback (most recent call last):
  File "Create pseudorandom calt feature.py", line 59, in <module>
    classglyphs = [ x.parent.name for x in thisFont.selectedLayers ], 
AttributeError: 'str' object has no attribute 'selectedLayers'
End`

I use Glyphs 2.0.0 on OSX Yosemite 10.10.3

**Comment by mekkablue** [comment]
Thank you for point this out. I fixed a couple of problems and cleaned up the code. The script should work now as expected.

**Comment by POXtheMusician** [comment]
Thanks a lot for the update, it works great now.
Thanks for all your work on glyphs scripts - they are very useful and helpful!

All best!
