### ISSUE TITLE
built positional calt feature, makes my Glyphs app crash

### ISSUE THREAD

**Issue by zwartekoffie** [mekkablue/Glyphs-Scripts#53]
Hi there,

Would love to use this script, but it keeps crashing my Glyphs app. I updated my OSX even to Yosemite, but no success. 
Does this feature need the Python modules? I hit the install module a couple of times, but it doesn't change to installed or anything. So I'm not a 100 percent sure they are installed.

![image](https://cloud.githubusercontent.com/assets/8177365/7455975/0b93f232-f281-11e4-954a-e4dc08035a06.png)

Glyphs version Version 2.0.0 (726)
OSX 10.10.3

Tested it also on a file that doesn't have any .fina/.init glyphs, also crashes Glyphs.

Thanks.

**Comment by mekkablue** [comment]
I will have a look.

**Comment by mekkablue** [comment]
I cannot reproduce an app crash with current app and system versions. Your app version is outdated, though. See if an update fixes it.

This script does not require the modules to be installed. You can see if the modules are installed by running 'print vanilla' in the Macro Window.

**Comment by bwtype** [comment]
Hi Mekkablue,

I'm having a similar problem as zwartekoffie. The script seems to run fine: it detects all my .medi glyphs and generates some classes and the calt, but the spinning wheel of death appears straight away. 

Any clues this might be happening?

Many thanks for all the hard work getting all this scripts available.

Glyphs Version 2.1.1 (782)
OSX 10.9.5
