### ISSUE TITLE
Report Area in Square Units

### ISSUE THREAD

**Issue by dadastudio** [mekkablue/Glyphs-Scripts#54]
Hi, 
when I run this script I got this:

Traceback (most recent call last):
  File "Report Area in Square Units.py", line 67, in <module>
    process( thisLayer )
  File "Report Area in Square Units.py", line 56, in process
    area = areaForLayer( thisLayer, PRECISION )
  File "Report Area in Square Units.py", line 52, in areaForLayer
    area += sizeOfSlice( cleanLayer, measurementHeight )
  File "Report Area in Square Units.py", line 30, in sizeOfSlice
    listOfIntersections = sliceIntersections( thisLayer, startPoint, endPoint )
  File "Report Area in Square Units.py", line 22, in sliceIntersections
    return measurementTool.calculateIntersectionsForLayer_startPoint_endPoint_( thisLayer, startPoint, endPoint )
AttributeError: No attribute calculateIntersectionsForLayer_startPoint_endPoint_

**Comment by mekkablue** [comment]
Thanks for reporting. Try the versions I just uploaded, please.

**Comment by dadastudio** [comment]
Ok it is working now. Thanks.

I draw a rectangle 100x100 and get the result: "Area of a: 10050.0 square units"

Why it is 10050.0 and not 10000.0?

**Comment by mekkablue** [comment]
Because the precision depends on the amount of measurements it takes. You can change the precision in the script itself, but it will slow down the script significantly. The default setting is a compromise between precision and speed.
