### ISSUE TITLE
Anchor Mover 2 and Respect Italic Angle problem

### ISSUE THREAD

**Issue by dadastudio** [mekkablue/Glyphs-Scripts#57]
Hi,

is there everything ok with this? It gives me some strange result when I try to move an anchor in my italic font. Moved anchor is way far too the right.

**Comment by mekkablue** [comment]
What exactly did you do?

**Comment by dadastudio** [comment]
I just  lowered top anchor in my italic font, and run Anchor Mover 2 script. I was expecting the script to position the anchor on cap  height , but the script positioned it about 90 pt to the right. 

I tried Your italicSkew function and I made it work simply by: italicSkew( mAnchor.x, yTarget-mAnchor.y )

**Comment by mekkablue** [comment]
I am looking into it.

**Comment by mekkablue** [comment]
Unfortunately, the problem at hand is more complicated than that. Will take a while to fix it.

**Comment by mekkablue** [comment]
Can you test the version I just uploaded?
