### ISSUE TITLE
Copy Layer to Layer Error

### ISSUE THREAD

**Issue by weiweihuanghuang** [mekkablue/Glyphs-Scripts#65]
Every glyph I get this error:

`local variable 'Key' referenced before assignment`

**Comment by mekkablue** [comment]
I cannot reproduce it. Can you send me the .glyphs file and explain the steps you are doing?

**Comment by weiweihuanghuang** [comment]
I've sent an email

**Comment by mekkablue** [comment]
Just uploaded a new version, which should fix this.
