### ISSUE TITLE
Copy Layer to Layer

### ISSUE THREAD

**Issue by MajusCorp** [mekkablue/Glyphs-Scripts#67]
Sent also to support@glyphsapp.com

G2.1.1 [775] OS X 10.10.4

1. I spent a few hours today troubleshooting the script problem reported previously via email and determined that if glyphsapp.py and glyphsapp.pyc are in the Scripts folder, the Copy Layer to Layer script will not work.

2. One other thing I discovered about the Copy Layer to Layer script is that if I use the script Select Same Color to select the glyphs to be copied, the Copy Layer to Layer script has to be run twice -- once, which copies the first glyph selected which was selected manually and a second time to copy the remainder of the selected glyphs which were selected by the other script.

**Comment by mekkablue** [comment]
1. Are you using multiple versions of the app side by side?
2. The problem is in the select script.

**Comment by schriftgestalt** [comment]
> I spent a few hours today troubleshooting the script problem reported previously via email and determined that if glyphsapp.py and glyphsapp.pyc are in the Scripts folder, the Copy Layer to Layer script will not work.

Please delete both files. They are a leftover and not needed.

**Comment by MajusCorp** [comment]
Rainer:

On 7/9/15 02:45, mekka blue wrote:
>
>  1. Are you using multiple versions of the app side by side?
>
No.
>
>  1. The problem is in the select script.
>
That is what I thought. At least there is a workaround for now.

Best,

George Thomas
