### ISSUE TITLE
Copy Kerning from Caps to SC and localized cyrillics

### ISSUE THREAD

**Issue by dadastudio** [mekkablue/Glyphs-Scripts#70]
Hi,

I have De-cy.loclBGR and others Bulgarian alternates in my font. The script makes names lowercase, but should make lowercase only first part, because SC counterpart has name de-cy.loclBGR.sc not de-cy.loclbgr.sc

this is a print from the script:
SC de-cy.loclbgr.sc not found in font (Uc De-cy.loclBGR exists)

**Comment by mekkablue** [comment]
Should be fixed now.

**Comment by dadastudio** [comment]
Almost. 

suffixOffset = returnName.find(".")
returnName = returnName[:suffixOffset].lower() + returnName[suffixOffset:]

when a glyph's name is a single letter, suffixOffset is -1 so returnName[:suffixOffset] returns nothing and got this dump:

  SC A.sc not found in font (Uc A exists)
  SC B.sc not found in font (Uc B exists)
  SC C.sc not found in font (Uc C exists)
  SC D.sc not found in font (Uc D exists)
...

maybe this would do the job:

suffixOffset = abs(returnName.find("."))

**Comment by mekkablue** [comment]
I uploaded a fix. Does this work?

**Comment by dadastudio** [comment]
I think so. I don't see anything to worry about. Thanks!
