### ISSUE TITLE
Dekink Masters error with Glyphs Version 2.2b (811)

### ISSUE THREAD

**Issue by dadastudio** [mekkablue/Glyphs-Scripts#74]
Traceback (most recent call last):
  File "Dekink Masters.py", line 63, in <module>
    raise e
TypeError: 'LayerSelectionProxy' object is not callable

**Comment by schriftgestalt** [comment]
Jan hat die Layer.selection in eine Property geändert. Du musst jetzt in allen Plugins und Scripten das hier machen:


try:
	selection = Layer.selection
except:
	selection = Layer.selection()
			
Georg

**Comment by mekkablue** [comment]
Umgekehrt:

    try:
    	selection = thisLayer.selection()
    except:
    	selection = thisLayer.selection
