### ISSUE TITLE
Guideline through selected nodes script deleted?

### ISSUE THREAD

**Issue by weiweihuanghuang** [mekkablue/Glyphs-Scripts#76]
https://github.com/schriftgestalt/Mekka-Scripts/blob/master/Guidelines/Guideline%20through%20Selected%20Nodes.py Plus it no longer works?

```
Traceback (most recent call last):
  File "Guideline through Selected Nodes.py", line 12, in <module>
    selection = thisLayer.selection()
TypeError: 'LayerSelectionProxy' object is not callable
```

 I liked it in the menu because I could have a shortcut

**Comment by mekkablue** [comment]
The script is not necessary any more, as it reduplicates a function already present in the UI. If you want to maintain your own, go back to a previous revision of the repository, and copy it to yours.
