### ISSUE TITLE
'Maciej y distribution' feature (in the 'Insert instances' script) causes Glyphs to crash (Glyphs 2.2.2 on OS X 10.10.5)

### ISSUE THREAD

**Issue by djebel-amila** [mekkablue/Glyphs-Scripts#85]
Hello,

Firstly, thank you for your tremendous work on these scripts.

I am trying to run the **Insert instances** script to generate the distribution of my weights according to Pablo’s curve. 

Alas, it only seems to work with *Maciej y distribution* box unchecked. 
Whenever selected, this option causes the *Glyphs* app to crash after a few seconds.

Thanks in advance for any piece of advice.

<img width="394" alt="capture d ecran 2016-01-20 a 12 34 45" src="https://cloud.githubusercontent.com/assets/16796103/12447794/3c0fa172-bf72-11e5-90fd-e9f0a38b86ea.png">

**Comment by mekkablue** [comment]
I cannot reproduce it, neither in 2.2, nor in 2.3b. The cause must be something else. Perhaps try reinstalling Glyphs, and reinstalling the Python modules in *Preferences > Addons > Modules*.
