### ISSUE TITLE
Show Next/Previous Intance.py not changing the Instance drop-down

### ISSUE THREAD

**Issue by weiweihuanghuang** [mekkablue/Glyphs-Scripts#87]
Not a big issue but I noticed it's no longer changing the display here:

![screen shot 2016-01-28 at 12 25 02 pm](https://cloud.githubusercontent.com/assets/1271897/12643073/2f161d9a-c5ba-11e5-9325-a7f31a62b8fe.png)

**Comment by mekkablue** [comment]
Cannot reproduce in Version 2.3b (844).
