### ISSUE TITLE
Floating Features, doesn't let you edit after activating a feature

### ISSUE THREAD

**Issue by weiweihuanghuang** [mekkablue/Glyphs-Scripts#88]
If I enable or disable a feature, the glyph I have selected is no longer editable, I have to exit the pen tool and go to Text tool then back to pen tool for it to work. Similarly the preview panel doesn't update.

Does it need a force redraw?

**Comment by schriftgestalt** [comment]
Jan has wrapped that a few days ago: https://github.com/schriftgestalt/GlyphsSDK/blob/master/ObjectWrapper/GlyphsApp.py#L6195

**Comment by weiweihuanghuang** [comment]
Well the script Floating Features script has a `reflow()` but look what happens after I run it, it stops letting me edit the glyph. http://quick.as/x6lkTnyWW

**Comment by schriftgestalt** [comment]
I fixed it.
