### ISSUE TITLE
Preflight Font crash

### ISSUE THREAD

**Issue by davelab6** [mekkablue/Glyphs-Scripts#91]
https://github.com/mekkablue/Glyphs-Scripts/blob/master/Test/Preflight%20Font.py crashes with https://github.com/Gue3bara/Lemonada-Arabic/blob/master/Lemonada-Arabic.glyphs (also discussed in https://github.com/Gue3bara/Lemonada-Arabic/issues/5)

**Comment by schriftgestalt** [comment]
We changed the API to acess the glyph info recently. And the script is not adapted, yet.

**Comment by mekkablue** [comment]
It should not crash the application, but report an error. The link to the .glyphs file gives me a 404.

**Comment by davelab6** [comment]
Its now at https://github.com/Gue3bara/Lemonada/blob/master/Lemonada.glyphs

**Comment by mekkablue** [comment]
Preflight is now laid to rest.
