### ISSUE TITLE
Delete all hints also deletes all Corner Components

### ISSUE THREAD

**Issue by rosaiani** [mekkablue/Glyphs-Scripts#98]
Hi Erich,
I've noticed that using Delete all Hints in Fonts also deletes all corners.
If you could maybe separate both operations, it would be amazing.

Loosing the corners means a lot of wasted time (especially if you're a fool like me and didn't save a version :))

Thanks!

**Comment by mekkablue** [comment]
I know. It is on my list.

> and didn't save a version

Grumble. Promise me you start saving versions from now.

**Comment by schriftgestalt** [comment]
The delete hints script in https://github.com/schriftgestalt/Glyphs-Scripts does keep the caps and corners.

**Comment by mekkablue** [comment]
Just updated,
