### ISSUE TITLE
Request to Floating Feature window

### ISSUE THREAD

**Issue by Tosche** [mekkablue/Glyphs-Scripts#99]
When I test my features, I often need to activate all default features first (typically liga and calt). Could you add a button to Floating Feature script that activates all features that should be on by default? I think that script is the best place is to add (of course it could exist on its own though).

**Comment by mekkablue** [comment]
That should be a separate script, _Activate Default Features_. Can you give me a list of all default features?

**Comment by impallari** [comment]
This? https://github.com/huertatipografica/huertatipografica-scripts/blob/master/Opentype/activateFeatures.py

**Comment by Tosche** [comment]
That doesn't seem to be the one I'm looking for (in fact, what's the difference from the mekkablue's script?). I'll come up with a list later.

**Comment by weiweihuanghuang** [comment]
What about 
https://gist.github.com/weiweihuanghuang/4c401d7b1c4ff0efd479be2358e1d890
You can add the features you need in featureList

**Comment by mekkablue** [comment]
@Tosche: Please make pull requests in the new script _Activate Default Features_. It’s in the same folder, next to _Floating Features_.
